// <auto-generated />
using System;
using Hodrac_MVP_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hodrac_MVP_Backend.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20260224124601_BestPeriodToVisitDataTypeChange")]
    partial class BestPeriodToVisitDataTypeChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestPeriodToVist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrencyId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("b91ca2ff-8634-449f-8597-3255ef112357"),
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = new Guid("c3babb6a-124a-4426-9673-d029bc042bd2"),
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            LanguageId = new Guid("ac4fcb33-e9b3-47b5-b8f0-3ed0a9f45928"),
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            LanguageId = new Guid("aab3f34b-cd27-4984-b87d-3f3448cdec86"),
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            LanguageId = new Guid("4c9814bd-ca69-4d75-b3d5-be79005c15aa"),
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("e2056386-1b66-463d-b83d-68efa37f388f"),
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            LanguageId = new Guid("c09fc98a-8a8a-4568-a500-6cfbc6b993ec"),
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("51a9a87c-96e6-4503-9646-e6c91dbf4490"),
                            LanguageName = "Basque"
                        },
                        new
                        {
                            LanguageId = new Guid("94bad170-7b69-4795-b3e4-db7a95958e37"),
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("06cbbf20-7da0-435d-aa90-12bc9a277e43"),
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            LanguageId = new Guid("80fa37b8-2b5c-45b1-99da-ec4696407bda"),
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            LanguageId = new Guid("9c94485f-7190-47df-bae3-101eed03ec44"),
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = new Guid("fa71fb12-6634-4cdb-83dd-dcc46bdab59e"),
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            LanguageId = new Guid("2c29ca45-e030-4c97-942b-942d1555006e"),
                            LanguageName = "Catalan"
                        },
                        new
                        {
                            LanguageId = new Guid("72c5bfd1-f823-44ad-809e-65dea957921c"),
                            LanguageName = "Cebuano"
                        },
                        new
                        {
                            LanguageId = new Guid("5527b328-6b55-4478-b543-a489c699f096"),
                            LanguageName = "Chichewa"
                        },
                        new
                        {
                            LanguageId = new Guid("fe23eb32-e003-42cf-a0fa-79ce7a7c7799"),
                            LanguageName = "Chinese (Mandarin)"
                        },
                        new
                        {
                            LanguageId = new Guid("4238e861-2342-4d04-b5d5-03c19d72e6a2"),
                            LanguageName = "Chinese (Cantonese)"
                        },
                        new
                        {
                            LanguageId = new Guid("61c042b4-b4bf-4cf1-a972-c0d34b31a496"),
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            LanguageId = new Guid("d6a0a518-1396-4750-bead-8b8e42a15b00"),
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageId = new Guid("d7b5b41a-20a8-45be-acec-6c1c00745339"),
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageId = new Guid("e1b398bb-7787-42b1-b005-a2afcb72b58d"),
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageId = new Guid("6c3cf49c-89c4-41e5-8628-4b1181df1f75"),
                            LanguageName = "Dari"
                        },
                        new
                        {
                            LanguageId = new Guid("05536d5d-9322-4193-b7aa-c6a2c9378f23"),
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageId = new Guid("1b0c8e3c-101d-4c57-9069-c883f8f11acd"),
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("d53af622-6fea-4588-bfcc-589d03d99958"),
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            LanguageId = new Guid("4a8ee8fe-1742-4439-91f8-c229f98100a4"),
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageId = new Guid("a07b632e-3e44-48f5-b517-463a6f794f67"),
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            LanguageId = new Guid("3a93d778-9931-441f-9050-0060a500366f"),
                            LanguageName = "Filipino"
                        },
                        new
                        {
                            LanguageId = new Guid("dd0f4938-092b-4f29-a610-de225a63073f"),
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageId = new Guid("8191423d-1a96-4579-8f41-652154b1bdaa"),
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("757664ca-5bb7-4305-a124-5c974083714a"),
                            LanguageName = "Frisian"
                        },
                        new
                        {
                            LanguageId = new Guid("61f4011c-bbcd-450f-a1c2-b602b9b8040e"),
                            LanguageName = "Galician"
                        },
                        new
                        {
                            LanguageId = new Guid("2b50a624-e33e-48ac-8282-3fca37d396cc"),
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("db298c9e-1b88-405a-9265-f4545031b820"),
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("d1be6506-ef54-4101-b50a-3064fcc366ab"),
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageId = new Guid("5103880a-6ad9-4572-95ce-c1a430872ad9"),
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            LanguageId = new Guid("410b8d79-48cc-42e8-abb2-2f09ca4d1854"),
                            LanguageName = "Haitian Creole"
                        },
                        new
                        {
                            LanguageId = new Guid("cc6201a6-de5c-463b-a8a6-938ed02fecf5"),
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            LanguageId = new Guid("0ac9d9c2-f41e-4997-8a43-6438a27df335"),
                            LanguageName = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = new Guid("e7c830db-9809-4711-8121-becae53ed516"),
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            LanguageId = new Guid("88d847e8-f23d-479d-8139-2c9610c300c2"),
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageId = new Guid("30cef719-ba38-4684-aaa5-b0cab69937f5"),
                            LanguageName = "Hmong"
                        },
                        new
                        {
                            LanguageId = new Guid("25c59964-a9c3-46a3-88e3-f33b43cedb13"),
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("979e07aa-4297-44e5-a667-0bf2b94ce2dd"),
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            LanguageId = new Guid("3648e774-71c1-4ae9-bd41-7c0e6f06e5e1"),
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            LanguageId = new Guid("c2f672ff-1f5f-4331-b266-bc3a4d3ce9fc"),
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            LanguageId = new Guid("b93b582d-06b0-4362-a955-02afa848f2aa"),
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageId = new Guid("01412afd-7362-4d85-a2f9-91492b58d32e"),
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("11babbaf-6640-4c62-ba77-43c3e4f96214"),
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("33a2fc66-b0fc-427c-a55e-915c54fed33e"),
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            LanguageId = new Guid("83e4c966-0fcd-4cd8-af33-1b167b787336"),
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageId = new Guid("c2fff818-64bf-4029-9524-b83edc140eb9"),
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("a6b17eee-9cff-4333-95be-5af0311cb217"),
                            LanguageName = "Khmer"
                        },
                        new
                        {
                            LanguageId = new Guid("aaa5ba23-ce7e-4bf3-aae1-3e5d62c08303"),
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = new Guid("acfb68ac-d67c-4ba8-aae9-ce6fbe1cc76a"),
                            LanguageName = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("19c3a11d-32c4-4865-a489-b2a6f1828910"),
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            LanguageId = new Guid("c1df383e-e0c7-4e7e-a638-a55669f021e3"),
                            LanguageName = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("e27994fe-c6f5-4c69-b508-840fe66f5675"),
                            LanguageName = "Lao"
                        },
                        new
                        {
                            LanguageId = new Guid("1c4212e0-715a-4dc8-aa6b-14a0c60149c5"),
                            LanguageName = "Latin"
                        },
                        new
                        {
                            LanguageId = new Guid("24ecf33f-a49f-4f2a-96d7-9d36bd6d025b"),
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageId = new Guid("a4bffed3-dc01-4c24-b056-63e39e11b4dd"),
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = new Guid("3168b8eb-c795-4cde-be36-1d9ca1c2f192"),
                            LanguageName = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = new Guid("2125f0f4-e646-44e5-871f-0dadeb88e300"),
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            LanguageId = new Guid("1c491c94-c0e7-4956-89cf-fa77d914c536"),
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            LanguageId = new Guid("f6865e38-c198-492c-9b65-f50f527fe06c"),
                            LanguageName = "Malay"
                        },
                        new
                        {
                            LanguageId = new Guid("fac6ee6e-c655-4efb-90c9-b97bb151c018"),
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageId = new Guid("8dba5eba-0c74-43fe-b0bc-dde9c3c52d19"),
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageId = new Guid("aae45399-e099-413c-9ddb-1fa3f8c3efff"),
                            LanguageName = "Maori"
                        },
                        new
                        {
                            LanguageId = new Guid("91cea7ab-339f-42ef-bd23-d47f03231e0d"),
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageId = new Guid("0bc306dc-bbcc-4749-9476-11300fae6ef1"),
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            LanguageId = new Guid("0e4bdeb5-faf8-4654-bee8-dd68e1c5d9ca"),
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            LanguageId = new Guid("3d2dd4c8-6302-4ac4-9b88-b77a93dcb494"),
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = new Guid("f35481fc-087e-46f9-b579-48cd3707f154"),
                            LanguageName = "Odia"
                        },
                        new
                        {
                            LanguageId = new Guid("7325a0db-f7f4-485c-817c-daef2dbdaa82"),
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            LanguageId = new Guid("7e262a4d-0168-4c8e-841b-62ddc8a6f98e"),
                            LanguageName = "Persian"
                        },
                        new
                        {
                            LanguageId = new Guid("62f9ca06-3cfa-4648-b9c7-f1328903c3e6"),
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageId = new Guid("ccc9e2d4-7509-484a-b51b-4db9bf2b32ac"),
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("de83c58a-13cb-49d6-8aaf-a19b31f7b67d"),
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageId = new Guid("b7f14619-6e52-43e7-90a9-c7012538d5ce"),
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageId = new Guid("87e2ee21-372b-4bc0-93e7-138bf0e4b9a1"),
                            LanguageName = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("ee7194f3-9496-4357-b085-4b4655a604e6"),
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            LanguageId = new Guid("fb3bd524-b83a-49c3-b89e-4893d16f9827"),
                            LanguageName = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = new Guid("f78cc0a5-a917-48b8-91b6-a85435b50980"),
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            LanguageId = new Guid("e1726f0e-dde1-46d0-9a26-f45fcd613e9f"),
                            LanguageName = "Sesotho"
                        },
                        new
                        {
                            LanguageId = new Guid("ad520015-640b-453a-aed9-2bfd24f2a7a6"),
                            LanguageName = "Shona"
                        },
                        new
                        {
                            LanguageId = new Guid("c98cc7bf-bfef-44e7-83b7-949311ff6520"),
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            LanguageId = new Guid("e1a665b1-f78f-4311-9ad2-297b8e6e59de"),
                            LanguageName = "Sinhala"
                        },
                        new
                        {
                            LanguageId = new Guid("de08e591-e85a-4d3f-abff-7fa03359823f"),
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageId = new Guid("3914a36e-0958-4f31-bb1e-a8e0b11d8d50"),
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageId = new Guid("392aef61-f6a8-4a50-a343-0e7fa1aa25a3"),
                            LanguageName = "Somali"
                        },
                        new
                        {
                            LanguageId = new Guid("b99c30c1-e812-4a4d-aa11-521822e46a1f"),
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("fc296d70-8157-4f3a-9b9f-c7b767a685f8"),
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            LanguageId = new Guid("f774ceaa-c020-48ea-8edb-b1f50b6c142f"),
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            LanguageId = new Guid("f194f52e-0000-4973-bd3b-0362e8b54025"),
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = new Guid("d0617370-e340-40d0-9e74-08aaad65178e"),
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("629d516d-b42e-4c1d-a1b4-b1142accb501"),
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageId = new Guid("7f323e25-2473-40b6-b53a-4625319bedc2"),
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            LanguageId = new Guid("36533734-874c-497a-8ad8-1a108a412c14"),
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageId = new Guid("d5ba07a9-e2e6-457e-84b7-bac4d270c8a3"),
                            LanguageName = "Thai"
                        },
                        new
                        {
                            LanguageId = new Guid("9ee69eaa-8641-45e4-8411-57e12dc93f82"),
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            LanguageId = new Guid("7a722b6a-b7ea-4bd4-8172-97df9c942e87"),
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            LanguageId = new Guid("a9a5bf21-a66e-411e-b7b1-dc452b4d0855"),
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("c1adc250-37f1-49fd-bd85-004eef60d4a6"),
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageId = new Guid("439e67cf-beff-4153-9943-fd8a3722dfb2"),
                            LanguageName = "Uyghur"
                        },
                        new
                        {
                            LanguageId = new Guid("3160df3e-bca6-4c70-b3e6-08bd51a48bde"),
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            LanguageId = new Guid("11cf5314-85cc-438a-9f66-098b05f26a90"),
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = new Guid("aaf8edf8-0dc1-4243-afd1-4ba8f5c205e4"),
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            LanguageId = new Guid("7768e035-e387-49f8-9d41-12eb37f85faa"),
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            LanguageId = new Guid("87982df4-5f92-484d-93c7-13804bd5a167"),
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            LanguageId = new Guid("eb4e5a02-72e5-459e-9458-22eac2e8fbdf"),
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            LanguageId = new Guid("80be6ad2-b65a-4d2f-bef4-70445b95543a"),
                            LanguageName = "Zulu"
                        });
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Navigation("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });
#pragma warning restore 612, 618
        }
    }
}
