// <auto-generated />
using System;
using Hodrac_MVP_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hodrac_MVP_Backend.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20260411162513_Wishlist")]
    partial class Wishlist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestPeriodToVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCost")
                        .HasColumnType("int");

                    b.Property<int>("MinCost")
                        .HasColumnType("int");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrencyId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryDay", b =>
                {
                    b.Property<Guid>("ItineraryDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("DayTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItineraryDayId");

                    b.HasIndex("WishlistId");

                    b.ToTable("ItineraryDays");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryItem", b =>
                {
                    b.Property<Guid>("ItineraryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemOrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItineraryItemId");

                    b.HasIndex("ItineraryDayId");

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("9e02ac00-1ded-42ac-b875-f82f9dadcc26"),
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = new Guid("1eb542c1-4fa9-43e5-b415-ff9c273d2d09"),
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            LanguageId = new Guid("3c56bedc-4d42-4f4e-88b1-e3bae2836074"),
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            LanguageId = new Guid("dbc4ba62-d029-4081-b03e-f80221f7b5f7"),
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            LanguageId = new Guid("b3560974-3e55-4fe2-9b55-1192af1bc8e1"),
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("5fa5475b-5fa1-44d0-b447-3d5f474d567e"),
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            LanguageId = new Guid("dfcfadc6-e857-4b9e-8e33-93041f3d67ed"),
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("130159fa-8886-4d7a-a25b-d73fa5584c30"),
                            LanguageName = "Basque"
                        },
                        new
                        {
                            LanguageId = new Guid("e58fd9f3-3c20-4d74-9528-fcdec4a3df83"),
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("280543e3-62b3-400b-bfa9-ad41f8b2af31"),
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            LanguageId = new Guid("92057243-2ca9-4054-868c-52c9a830a8b7"),
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            LanguageId = new Guid("a5d9eb0d-27b7-4766-90be-b9f261ef25f8"),
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = new Guid("cd948f89-47ad-41e1-9f66-3212ca328bd2"),
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            LanguageId = new Guid("20d5e34d-567a-4a16-95ec-b16aed6d8cd7"),
                            LanguageName = "Catalan"
                        },
                        new
                        {
                            LanguageId = new Guid("e7b2b417-d5fb-4ac0-aa48-4588f04245f8"),
                            LanguageName = "Cebuano"
                        },
                        new
                        {
                            LanguageId = new Guid("9b78d272-a0e5-4c36-97f5-aaaf39331e55"),
                            LanguageName = "Chichewa"
                        },
                        new
                        {
                            LanguageId = new Guid("7ff070d6-1be9-4e67-b3b1-6156d33a675a"),
                            LanguageName = "Chinese (Mandarin)"
                        },
                        new
                        {
                            LanguageId = new Guid("c277e21c-0e34-4c65-bd35-761d0fd8c90b"),
                            LanguageName = "Chinese (Cantonese)"
                        },
                        new
                        {
                            LanguageId = new Guid("3124af59-a951-4c7a-b818-438ce7e92641"),
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            LanguageId = new Guid("2f757c9b-6cb5-4acd-ae88-3af38eacb250"),
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageId = new Guid("d338555b-4a3b-4d8d-acc4-5ec810ac87d7"),
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageId = new Guid("c616fcd1-b612-4394-ba63-008660d4b411"),
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageId = new Guid("e47407ea-8679-4f16-ba64-6081570e6b65"),
                            LanguageName = "Dari"
                        },
                        new
                        {
                            LanguageId = new Guid("dec73be7-d24c-4a80-aa60-3228d3651f68"),
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageId = new Guid("60e5012d-c77c-4b45-ac5e-20a7090f2691"),
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("46e4a4f2-9eb1-455c-b782-82794dbf8d33"),
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            LanguageId = new Guid("6a193c63-5d79-4e26-a781-b8582b7defd8"),
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageId = new Guid("1c6ab40f-2175-4d23-9ab0-73344fd30d72"),
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            LanguageId = new Guid("ae66ff49-078c-4384-a279-a259deb437fc"),
                            LanguageName = "Filipino"
                        },
                        new
                        {
                            LanguageId = new Guid("e8c0b463-f66f-4ac6-8e8a-1dbe54a0192d"),
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageId = new Guid("8bb72044-bda2-4b22-b8ba-41a0abbbf75e"),
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("6e26bfa0-1e69-41ea-85c9-e40854bee322"),
                            LanguageName = "Frisian"
                        },
                        new
                        {
                            LanguageId = new Guid("d3e7eb31-fe1b-4b9e-9987-9288f2ae1624"),
                            LanguageName = "Galician"
                        },
                        new
                        {
                            LanguageId = new Guid("bfd72f1c-3de4-4e86-bb4c-fa607b9674db"),
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("e67d9c30-6b5c-4a1e-aaf7-582ca5bcb6f2"),
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("d9a54885-8b83-491e-a8ab-ab993bb93113"),
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageId = new Guid("d9b4d651-42aa-4062-9794-91fd44a24112"),
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            LanguageId = new Guid("aef614b7-858c-43e7-9e22-35a1f4c92ce4"),
                            LanguageName = "Haitian Creole"
                        },
                        new
                        {
                            LanguageId = new Guid("17d3cf79-5243-4865-b9ea-73055e6359c2"),
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            LanguageId = new Guid("ccaaf72c-4ffa-4af9-ad49-ae4512493603"),
                            LanguageName = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = new Guid("555c5939-28ee-4c15-b2c3-2e4007f2f8da"),
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            LanguageId = new Guid("89d52cd9-a7ed-473f-b123-b8dc9618dd2d"),
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageId = new Guid("ae0a4312-3a36-4acd-b1bb-da3f07e856a5"),
                            LanguageName = "Hmong"
                        },
                        new
                        {
                            LanguageId = new Guid("5f10317a-1151-4c1c-a255-7192501b56c2"),
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("63918524-ec6f-44a7-b696-29c3f314b9b9"),
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            LanguageId = new Guid("4e65f052-7dc5-4666-898c-2e74f3b8d39a"),
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            LanguageId = new Guid("f387dab8-6d4e-4222-843a-92d4112f7aa3"),
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            LanguageId = new Guid("0b66218f-9ae2-4993-a1ec-f012890dca95"),
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageId = new Guid("a69836a8-e817-444a-9e95-5e93a5595234"),
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("acfbd143-4bf7-46c1-afd1-d015e0a308d7"),
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("eda3f1f8-cb38-4bf2-82e7-893f0ac93efb"),
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            LanguageId = new Guid("a76d4ce1-d83c-4de9-b1e6-c2e57d79577a"),
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageId = new Guid("9d8d274d-7e74-4036-8f9f-8eb226081eaa"),
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("32db97ab-8a11-41c0-a69d-982bfd2f1215"),
                            LanguageName = "Khmer"
                        },
                        new
                        {
                            LanguageId = new Guid("2d7aa60d-6eec-4b1d-bcf8-8b13eb0f5fab"),
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = new Guid("2bcad464-e95c-4b5f-8062-9d709a629708"),
                            LanguageName = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("8d84076a-8776-4f23-b0e9-ab1255935483"),
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            LanguageId = new Guid("de8b86a1-ff67-4004-977e-84e5212c5ae8"),
                            LanguageName = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("1fe42176-de3d-4c99-997c-672ad9b3a660"),
                            LanguageName = "Lao"
                        },
                        new
                        {
                            LanguageId = new Guid("a22f8971-ede5-4fed-a765-643492fa799b"),
                            LanguageName = "Latin"
                        },
                        new
                        {
                            LanguageId = new Guid("2094c1c4-209a-49f0-b06d-e05ea1f43f08"),
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageId = new Guid("baf7088d-3c02-4c1a-8c55-f24ba0f3a4fa"),
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = new Guid("68e1e38f-fa5f-4c22-830a-3b2f4f2abe5a"),
                            LanguageName = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = new Guid("d977e163-d74c-4e07-a75c-68eccb938496"),
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            LanguageId = new Guid("b01ca507-434b-4feb-b6e2-295c80322b4b"),
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            LanguageId = new Guid("151ad4ec-99d6-4eb7-bbf1-c76e3c72993c"),
                            LanguageName = "Malay"
                        },
                        new
                        {
                            LanguageId = new Guid("53c5aae8-2b98-4ea2-abcc-34833216dfc2"),
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageId = new Guid("db0cd23d-44f1-4b08-a6a8-a8bf6ece9f6d"),
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageId = new Guid("9d1d549d-75b5-4e4e-a39c-e03a427d3719"),
                            LanguageName = "Maori"
                        },
                        new
                        {
                            LanguageId = new Guid("d48441f6-6e28-443d-a5bf-3a6ee96862cc"),
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageId = new Guid("e45b87ae-e407-41f6-aa7c-eb6ab1e16460"),
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            LanguageId = new Guid("f891dea1-935a-4f2a-a389-ad79d9d62461"),
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            LanguageId = new Guid("d1f3c6cd-9052-4bc6-b638-dda2630c1ccd"),
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = new Guid("1ed47395-5527-46c7-84e9-ca228e4a9759"),
                            LanguageName = "Odia"
                        },
                        new
                        {
                            LanguageId = new Guid("38e0f46c-d34b-4391-820e-9d266c51953c"),
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            LanguageId = new Guid("fd555264-6222-4eb1-87db-5defe97591f4"),
                            LanguageName = "Persian"
                        },
                        new
                        {
                            LanguageId = new Guid("8e3cbe99-ea67-4594-a8ba-5a6dab4b3d2b"),
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageId = new Guid("7179bbdd-d25e-42e5-a53a-d152a56fc1b4"),
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("b53c3742-3902-4f82-8650-7fddecb77984"),
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageId = new Guid("dbabab2c-0008-4985-81c4-f9ab9144b2a6"),
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageId = new Guid("ab6d4f72-a3d2-4031-95fd-d3156ce12151"),
                            LanguageName = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("16a2b4ab-069e-4081-9754-0d7d8e3eaf09"),
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            LanguageId = new Guid("0fc143bb-4e10-4a40-bfb9-1b0aa5e85553"),
                            LanguageName = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = new Guid("5656c403-e9c6-4a5d-8e24-58ab66814392"),
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            LanguageId = new Guid("b661f04a-3623-4ba4-9efa-57d314611ed7"),
                            LanguageName = "Sesotho"
                        },
                        new
                        {
                            LanguageId = new Guid("5391d638-e782-4bda-8a6b-4102db912f6d"),
                            LanguageName = "Shona"
                        },
                        new
                        {
                            LanguageId = new Guid("23fbdede-2c85-421d-ac4f-c95bd325d529"),
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            LanguageId = new Guid("bce55907-2136-457e-b64d-1c59fac76245"),
                            LanguageName = "Sinhala"
                        },
                        new
                        {
                            LanguageId = new Guid("eee93458-9aab-44f3-a5b3-5cf77933f719"),
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageId = new Guid("ab940444-2744-4da5-80a8-9c5e031cc34b"),
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageId = new Guid("18421ef6-66f0-4944-8059-765278e2999e"),
                            LanguageName = "Somali"
                        },
                        new
                        {
                            LanguageId = new Guid("3f08a680-ff99-487d-b537-7abe8c1eeb7a"),
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("45c1b67f-e910-4ee1-8132-61f36e4d620b"),
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            LanguageId = new Guid("f98e49ac-7e8a-4ccc-b2ec-158c98ba40cb"),
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            LanguageId = new Guid("b66fb306-3d1c-4f7c-b0b9-049c0ff268c3"),
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = new Guid("068e182a-a3af-4c7b-bdc0-5228a23af7ba"),
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("e20bda79-da2c-4c33-a8ba-a8ef99c0c11e"),
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageId = new Guid("52bbbe29-fd7a-4db2-ae0e-54ee1eed466c"),
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            LanguageId = new Guid("a7f0a37d-630e-4359-a692-c5f893f15b54"),
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageId = new Guid("6bb9f6f7-8a7a-4506-bd8a-26e4dc7d3eda"),
                            LanguageName = "Thai"
                        },
                        new
                        {
                            LanguageId = new Guid("919946dc-0b21-4fd7-817d-af180f4170c5"),
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            LanguageId = new Guid("3879ccf7-f18a-49d5-a565-1fb290989254"),
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            LanguageId = new Guid("f31723d6-dd0b-4f63-9eef-f852998891b6"),
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("c5ae2811-a6e9-4d99-b784-f6a7ea7ef1cf"),
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageId = new Guid("64baa25b-723f-45b1-a05e-f473c5e60f40"),
                            LanguageName = "Uyghur"
                        },
                        new
                        {
                            LanguageId = new Guid("9fa5eb96-c405-4fb9-8f0e-69bf8f31aa0c"),
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            LanguageId = new Guid("1fddfbb5-7abe-4c3a-a8d5-47ca8b5d0765"),
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = new Guid("84c23132-849c-497d-a4a7-959cc9ea8bca"),
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            LanguageId = new Guid("bba5781e-21a3-4455-af13-447aeaf7664f"),
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            LanguageId = new Guid("5dd48e49-81d2-46f3-a02c-0b1423efeed9"),
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            LanguageId = new Guid("a98906ea-1a9d-4ce5-835c-df22d053bd7b"),
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            LanguageId = new Guid("a9919311-d085-4a8f-ac3b-827133ba24a8"),
                            LanguageName = "Zulu"
                        });
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Wishlist", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeopleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortStory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<string>("WishlistDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WishlistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WishlistId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.WishlistDestination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WishlistDestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DestinationId", "WishlistId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistDestinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryDay", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Wishlist", "Wishlist")
                        .WithMany("ItineraryDays")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryItem", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.ItineraryDay", "ItineraryDay")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.WishlistDestination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("WishlistDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistDestinations")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Navigation("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");

                    b.Navigation("WishlistDestinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryDay", b =>
                {
                    b.Navigation("ItineraryItems");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Wishlist", b =>
                {
                    b.Navigation("ItineraryDays");

                    b.Navigation("WishlistDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
