// <auto-generated />
using System;
using Hodrac_MVP_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hodrac_MVP_Backend.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20260302161553_ChangeDataTypeCostRangeDestination")]
    partial class ChangeDataTypeCostRangeDestination
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestPeriodToVist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrencyId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("d6b43c51-b78f-445d-858e-4a22bc2f2ddc"),
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = new Guid("930ef799-2403-4984-9710-d8c884ab015f"),
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            LanguageId = new Guid("63cc32b1-df58-4e95-bf62-ef0b27a467e1"),
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            LanguageId = new Guid("2914cedd-fa18-4706-b95c-66e6dd45215c"),
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            LanguageId = new Guid("21266530-9401-422f-9ae3-4609629cc94f"),
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("e03c68c6-e3bf-40f8-963f-afbbc00ce30e"),
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            LanguageId = new Guid("8d1e5332-599b-4458-b5fc-2196796af96c"),
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("57aa169b-1fa0-4983-b9b4-ed41491ff117"),
                            LanguageName = "Basque"
                        },
                        new
                        {
                            LanguageId = new Guid("c45aa541-cc33-4490-90e8-e42a38567cd0"),
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("d7cade4b-bacf-4b40-ac29-80ad2f0c27a5"),
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            LanguageId = new Guid("4b863aa5-962e-4076-8d37-67ce8debac20"),
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            LanguageId = new Guid("26259be8-ca90-48f9-b0ed-fea3436a1037"),
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = new Guid("ad454f73-b4d8-405d-a318-49e2015e0fa4"),
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            LanguageId = new Guid("e52af248-c501-4323-b055-3a66c1942509"),
                            LanguageName = "Catalan"
                        },
                        new
                        {
                            LanguageId = new Guid("fb41d0f2-76e7-48eb-82a1-47b80771f7e2"),
                            LanguageName = "Cebuano"
                        },
                        new
                        {
                            LanguageId = new Guid("37f71856-c7ba-40f5-9e0a-b5e693754cd1"),
                            LanguageName = "Chichewa"
                        },
                        new
                        {
                            LanguageId = new Guid("ddff6c0d-cb55-42f2-a639-c5b33ad05917"),
                            LanguageName = "Chinese (Mandarin)"
                        },
                        new
                        {
                            LanguageId = new Guid("8e78ddf6-1d3d-4916-9c08-9d42b144920a"),
                            LanguageName = "Chinese (Cantonese)"
                        },
                        new
                        {
                            LanguageId = new Guid("ad6819d9-5f6f-4f68-9bbf-8731f0abb2ac"),
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            LanguageId = new Guid("a85f4d94-0d8b-4cda-bcb9-57710ee051aa"),
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageId = new Guid("b2dbacd7-ab8f-4a89-929e-64473de6a7ae"),
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageId = new Guid("d3f70b58-f1c2-40cb-b1c2-e2a8b588e417"),
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageId = new Guid("28519be2-e0c6-46f2-813d-d5c80c6630fb"),
                            LanguageName = "Dari"
                        },
                        new
                        {
                            LanguageId = new Guid("a1320b60-5270-4170-9f38-249405c47dd6"),
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageId = new Guid("cf07bb31-d5f8-4fc2-98f6-8ccaa60feee1"),
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("aefb0dc8-6a5e-4387-b1a6-ad2038d37e19"),
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            LanguageId = new Guid("e2840480-6a1d-4a3f-8a9a-84fac9fb1e4f"),
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageId = new Guid("5560d400-02ef-449c-9419-b445ece7023c"),
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            LanguageId = new Guid("80974060-7b90-4efb-86ff-566cb107fb49"),
                            LanguageName = "Filipino"
                        },
                        new
                        {
                            LanguageId = new Guid("23b535dd-5f67-413d-981d-2f2a31684ae7"),
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageId = new Guid("129d60d4-494e-444d-b034-bf44db28711e"),
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("5c69f1ed-e0ec-448a-9bd4-c6eaff7fdddf"),
                            LanguageName = "Frisian"
                        },
                        new
                        {
                            LanguageId = new Guid("f74b3145-9ac4-46bf-b8a1-6749d44f2fdc"),
                            LanguageName = "Galician"
                        },
                        new
                        {
                            LanguageId = new Guid("acbead07-bec0-4cef-ac9d-35534bebec3e"),
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("782bf3e4-fbb9-41df-aa1e-6cbbdba96752"),
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("3f93d630-e594-4be3-bbbd-07c4474cf129"),
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageId = new Guid("831260de-74b6-4bb1-bd6c-cf90687c1c7b"),
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            LanguageId = new Guid("7cb0d4a0-9d9d-4b63-80a3-0abe48fdfc88"),
                            LanguageName = "Haitian Creole"
                        },
                        new
                        {
                            LanguageId = new Guid("40000518-ad84-490f-aa13-94603bdb89a5"),
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            LanguageId = new Guid("9ff236d8-8dd9-442b-9848-4971c65cb15c"),
                            LanguageName = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = new Guid("94a12dd9-e58e-4b70-9bd2-cf4b5f96a24a"),
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            LanguageId = new Guid("435f08d2-8ff1-4d36-b651-d48a86ceadb4"),
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageId = new Guid("2e519921-075d-47b9-aec1-3388ea434828"),
                            LanguageName = "Hmong"
                        },
                        new
                        {
                            LanguageId = new Guid("c7c56c78-f97d-4190-93d0-2eed38dc4da8"),
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("ccfac95b-8f1c-4c17-8372-62ebea47309e"),
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            LanguageId = new Guid("66578a9a-f421-4ae1-8267-fb70591359c0"),
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            LanguageId = new Guid("5c80b296-58b9-4070-bb5e-df23da3baf7e"),
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            LanguageId = new Guid("378ebc49-016e-40c1-9aa2-77ea6e9e9424"),
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageId = new Guid("976992cc-c84f-4f1a-b81f-b88f63ba4898"),
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("75355653-7753-41d1-8d1e-6f51c956afb5"),
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("95580509-51d4-454e-aaa9-0e5992ee16cd"),
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            LanguageId = new Guid("d0d92530-e302-42fd-8ee1-81fa2cc9f7b1"),
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageId = new Guid("ce23935d-9832-48bf-9af6-768cc1e7fb62"),
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("1b71c892-85ac-4838-9759-9991ea441f98"),
                            LanguageName = "Khmer"
                        },
                        new
                        {
                            LanguageId = new Guid("e58536c9-a474-484e-862c-ed406be13c2b"),
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = new Guid("c6297fc8-96d0-407f-99f2-f33421212d00"),
                            LanguageName = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("cc0ed978-257a-4d02-a6db-3864dbf24b32"),
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            LanguageId = new Guid("bc79afbf-c12a-4da5-9216-11ecb9b646f1"),
                            LanguageName = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("e033fae6-8c75-4efe-b1ea-ab1d0d5de384"),
                            LanguageName = "Lao"
                        },
                        new
                        {
                            LanguageId = new Guid("22c2d5ed-1aec-4b18-a41a-fcc2ddf3cac6"),
                            LanguageName = "Latin"
                        },
                        new
                        {
                            LanguageId = new Guid("f495aa8d-eae5-4808-bfd9-ba77a13d0d1d"),
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageId = new Guid("3ea1ec7b-9e44-4427-a962-5e4cf147e036"),
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = new Guid("96eeca53-c985-4c5d-9da4-6970a89b01bd"),
                            LanguageName = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = new Guid("42b9603c-6e8e-4410-a7f0-37a173cb7555"),
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            LanguageId = new Guid("744d7743-94c4-4573-bcb9-f45411babce3"),
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            LanguageId = new Guid("aa6965c8-5d7f-49e9-b7a4-55b5643de3e6"),
                            LanguageName = "Malay"
                        },
                        new
                        {
                            LanguageId = new Guid("ffd245ed-7a40-4e90-8efa-c30e9825c14b"),
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageId = new Guid("08310dc5-6bf1-422d-91ef-d4f475b0995b"),
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageId = new Guid("b7c2d42c-8a96-4458-bdc0-ba81bb5a006e"),
                            LanguageName = "Maori"
                        },
                        new
                        {
                            LanguageId = new Guid("f580f4c3-f108-44ee-92ae-c32d464b73c2"),
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageId = new Guid("1ba8625f-0f43-4eb2-8c31-03a8a80f0c68"),
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            LanguageId = new Guid("39027913-7ff5-44ce-bae8-5bbedb88e0dc"),
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            LanguageId = new Guid("ab3a912d-3948-4857-8d40-40f76de91c0f"),
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = new Guid("6b233426-2026-4174-9d58-8e2ce32e30af"),
                            LanguageName = "Odia"
                        },
                        new
                        {
                            LanguageId = new Guid("c3fdbbeb-6c87-4f4b-97ae-81ae1de5ace4"),
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            LanguageId = new Guid("2d988356-ff2a-4f94-b7b0-5766432f0bb8"),
                            LanguageName = "Persian"
                        },
                        new
                        {
                            LanguageId = new Guid("974a7012-80ca-4989-87a1-46d8b73660ca"),
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageId = new Guid("02511933-0358-4dd8-a2b7-da53aa74367f"),
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("5b827a6e-44d5-4c1c-aaed-7429b3d83cad"),
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageId = new Guid("f7b59119-0d3e-413d-a3be-1dd36677bfff"),
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageId = new Guid("ee0d53ff-382d-4496-905e-0117953ae6cc"),
                            LanguageName = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("31865986-656c-4dd7-bc8f-bb889ea69ca0"),
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            LanguageId = new Guid("f8d7e837-6dc5-44d9-85dd-4cbf38902082"),
                            LanguageName = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = new Guid("96789b9f-0023-47ab-920a-bb3aae8ba8af"),
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            LanguageId = new Guid("4040d565-ec30-4b7c-a758-90d66abc5028"),
                            LanguageName = "Sesotho"
                        },
                        new
                        {
                            LanguageId = new Guid("48b7858c-2dd3-460c-a73d-b15922b66961"),
                            LanguageName = "Shona"
                        },
                        new
                        {
                            LanguageId = new Guid("9161e792-6682-4321-bf12-420cf2954a58"),
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            LanguageId = new Guid("533cc533-dc7c-4f46-8014-96c5d453bba1"),
                            LanguageName = "Sinhala"
                        },
                        new
                        {
                            LanguageId = new Guid("c6feb32d-f85d-4267-9933-366a866f6fc9"),
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageId = new Guid("e4def5df-b845-405e-b1e4-f964ddb4b0e5"),
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageId = new Guid("a255448d-036f-48ca-909d-437958283f9a"),
                            LanguageName = "Somali"
                        },
                        new
                        {
                            LanguageId = new Guid("e29ee8f4-a6a5-45a2-8dd4-20e63a5d48f9"),
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("75faae27-e950-4807-b7dc-e868d2477619"),
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            LanguageId = new Guid("6f8cfe2f-2eda-4d22-881e-c46fd9ddf84e"),
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            LanguageId = new Guid("c2eacc68-2658-4f3b-89de-b4c92b2f5250"),
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = new Guid("6ecf6707-6990-4813-aee4-43779bfedeec"),
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("9b267c1c-5b31-4296-a8bd-2775ca63f3f3"),
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageId = new Guid("36b466ba-fa12-4e07-b40e-d1d0a93e07d1"),
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            LanguageId = new Guid("7c98abdb-6ed2-4bbf-838c-a7748f8de503"),
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageId = new Guid("bba0f0d3-06b0-4352-83a4-5a25e57caba7"),
                            LanguageName = "Thai"
                        },
                        new
                        {
                            LanguageId = new Guid("5f25fdc4-651f-49a0-8e57-0f7f7a088e8d"),
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            LanguageId = new Guid("df5a611e-68ce-4dd3-9608-95940399c73e"),
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            LanguageId = new Guid("7b212f0c-143f-4bd4-9702-632366227797"),
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("720a8173-8489-4bea-9276-8c77e9dd47a9"),
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageId = new Guid("f1f512ae-da5d-4b30-8e9b-10831e04e2c1"),
                            LanguageName = "Uyghur"
                        },
                        new
                        {
                            LanguageId = new Guid("e07d7474-4a99-41c7-b452-78a9f6788dfb"),
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            LanguageId = new Guid("38c116b6-6133-44f5-8a99-cb5b5bb0f7ea"),
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = new Guid("a19f5abb-7f9d-4bee-b0d6-60fca1fa3430"),
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            LanguageId = new Guid("c04cd5ad-f932-4997-9b40-b8c6e6b765d0"),
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            LanguageId = new Guid("db2cc425-d953-4d58-b83a-13ac87a7afd1"),
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            LanguageId = new Guid("28363425-824b-40d5-9985-06365484bfbe"),
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            LanguageId = new Guid("5b32bf32-94ee-4675-a579-1822f42fe12c"),
                            LanguageName = "Zulu"
                        });
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Navigation("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });
#pragma warning restore 612, 618
        }
    }
}
