// <auto-generated />
using System;
using Hodrac_MVP_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hodrac_MVP_Backend.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20260413164914_NewLanguageGuna")]
    partial class NewLanguageGuna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestPeriodToVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCost")
                        .HasColumnType("int");

                    b.Property<int>("MinCost")
                        .HasColumnType("int");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrencyId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryDay", b =>
                {
                    b.Property<Guid>("ItineraryDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("DayTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItineraryDayId");

                    b.HasIndex("WishlistId");

                    b.ToTable("ItineraryDays");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryItem", b =>
                {
                    b.Property<Guid>("ItineraryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemOrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItineraryItemId");

                    b.HasIndex("ItineraryDayId");

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("349ccddb-d1c3-4265-b5bd-178dfc2572e8"),
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = new Guid("74b0f271-a54a-46b9-aeaa-2b418c890764"),
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            LanguageId = new Guid("05922628-7083-4f79-ab26-171f7a313325"),
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            LanguageId = new Guid("f50c4294-b156-4b42-93f4-3b27a2b78f5d"),
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            LanguageId = new Guid("4fabe352-becf-456b-a112-b129ebb18ee5"),
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("4a3d82ee-03e9-45c7-99d0-0db1f5243176"),
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            LanguageId = new Guid("da269b2d-1231-4c35-9f62-c41702e969fc"),
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("5dcd677d-bf64-4df2-9ffc-b1e68eacac2d"),
                            LanguageName = "Basque"
                        },
                        new
                        {
                            LanguageId = new Guid("c95cb4ee-679a-42b1-babf-91f6b16d9e87"),
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("e2fbefa0-99ea-4130-820e-070fc7bfc738"),
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            LanguageId = new Guid("adc0f3d3-d6ad-4de9-b71f-70a6425c67ad"),
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            LanguageId = new Guid("965a8833-25f2-4b9c-a573-1ab094b464fb"),
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = new Guid("9d2a8a13-d0c0-4354-869a-35e537212b3f"),
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            LanguageId = new Guid("5567bc70-4cc3-4052-bece-10bec63edcc3"),
                            LanguageName = "Catalan"
                        },
                        new
                        {
                            LanguageId = new Guid("99f9901a-10d5-4d6c-aa20-cc456b14fa12"),
                            LanguageName = "Cebuano"
                        },
                        new
                        {
                            LanguageId = new Guid("e41d3335-795c-4997-8871-82221f0fe47e"),
                            LanguageName = "Chichewa"
                        },
                        new
                        {
                            LanguageId = new Guid("1c9e9358-41b4-4266-900d-fe66b974a86f"),
                            LanguageName = "Chinese (Mandarin)"
                        },
                        new
                        {
                            LanguageId = new Guid("9776e26b-cb14-4911-bc13-97face0786a5"),
                            LanguageName = "Chinese (Cantonese)"
                        },
                        new
                        {
                            LanguageId = new Guid("4c5eb842-1762-46a2-9961-275d6aec3044"),
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            LanguageId = new Guid("49ce60f2-e31e-40f9-a01f-d244518db128"),
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageId = new Guid("7807b9d5-2e57-48d2-9596-e20eac4b72c4"),
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageId = new Guid("b4d17679-3e26-4146-8035-79d1d9dc7b82"),
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageId = new Guid("328bd079-9c89-41ab-9e56-41c14d005898"),
                            LanguageName = "Dari"
                        },
                        new
                        {
                            LanguageId = new Guid("1f354381-b111-4d7b-9211-1fe198247cf8"),
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageId = new Guid("8391a510-9c7c-40ce-9ca9-151f5de3f86c"),
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("b4e07049-c909-4cfe-86c8-a0385fe1ca05"),
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            LanguageId = new Guid("a4283e21-9698-468c-92b4-deecb15315bf"),
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageId = new Guid("4e8a3445-6cf8-4f06-88bd-17a37a5b8a1a"),
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            LanguageId = new Guid("7944e2df-7a1b-4b35-8656-33da65c1073d"),
                            LanguageName = "Filipino"
                        },
                        new
                        {
                            LanguageId = new Guid("54a2263d-654a-407b-b909-0df6d295453f"),
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageId = new Guid("92a885cf-2dcb-4d77-92a7-7bf6372d3e9a"),
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("017dc08e-b320-49cf-82ed-96a220ae5892"),
                            LanguageName = "Frisian"
                        },
                        new
                        {
                            LanguageId = new Guid("9199de2d-c578-46f3-9b12-fb70ac26a31d"),
                            LanguageName = "Galician"
                        },
                        new
                        {
                            LanguageId = new Guid("1c0d84d9-d1a3-4a94-8507-eff0b6bf6201"),
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("56ed3a47-c919-4633-9c43-33086417be48"),
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("b124ce34-3d50-438b-b48f-d147f92da9f5"),
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageId = new Guid("51806166-d118-40d3-b637-c49efc9ebc2b"),
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            LanguageId = new Guid("c6e327fc-474d-43b6-9b23-1866d45ad8be"),
                            LanguageName = "Haitian Creole"
                        },
                        new
                        {
                            LanguageId = new Guid("76464541-5d1b-4b22-b0bc-a486405b6b5e"),
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            LanguageId = new Guid("59141152-e324-4c38-9ecf-cbc55b0ae7b0"),
                            LanguageName = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = new Guid("bc4da2c5-2515-456c-a7ed-7391fe0913ff"),
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            LanguageId = new Guid("e45415ec-f7da-4cae-8c9e-e863c66289dd"),
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageId = new Guid("cfae6eb0-72c9-414a-a68f-84b054130130"),
                            LanguageName = "Hmong"
                        },
                        new
                        {
                            LanguageId = new Guid("918bdfc0-fe14-447f-ba32-a786beac197a"),
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("dda01911-e4c1-4e43-9cc0-9d110ba2f6a0"),
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            LanguageId = new Guid("f283cf71-6176-491d-aa34-e4062961049f"),
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            LanguageId = new Guid("3abdc949-2a70-4608-b2f8-d87754ed4359"),
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            LanguageId = new Guid("6eb2b6f1-6b8b-47c3-af85-71a5d8f0994d"),
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageId = new Guid("c33922db-0460-4a4a-85b6-7b962c6e11dd"),
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("bdbb365a-6290-4c83-9b00-1f4539428866"),
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("6d380339-f873-488e-a7e5-e3351d251021"),
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            LanguageId = new Guid("42554d08-cd6d-4ca2-b644-8a178d8d8b49"),
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageId = new Guid("b29bdc07-819d-43e3-b42b-8c99a25907bd"),
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("d3aece54-c660-404f-ba3e-c8e2b147b3df"),
                            LanguageName = "Khmer"
                        },
                        new
                        {
                            LanguageId = new Guid("4508f954-afb3-4739-b3e3-36280d112437"),
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = new Guid("d59af725-636a-470f-8281-fcf7e15f44ec"),
                            LanguageName = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("98015bcd-c8fe-495b-9083-bd95991ad0fd"),
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            LanguageId = new Guid("b2983695-ce08-4de7-9961-8508da2658f8"),
                            LanguageName = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("bc626e75-573d-42a3-8d4b-fe4dd173fa6e"),
                            LanguageName = "Lao"
                        },
                        new
                        {
                            LanguageId = new Guid("e4c5a460-dc5e-4938-988d-309ccd17ecc9"),
                            LanguageName = "Latin"
                        },
                        new
                        {
                            LanguageId = new Guid("b0591316-e74b-4bb9-aae1-50797ce4f003"),
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageId = new Guid("c8ba950e-9f07-42ad-9ae5-87adc652d918"),
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = new Guid("bce1c36d-74ad-4d4f-ab6c-d5e525de1dc4"),
                            LanguageName = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = new Guid("b41c82cc-ac6c-435a-aba6-2ba19ac26c57"),
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            LanguageId = new Guid("6982f8fc-fc75-46a9-a813-bb2c1fd83023"),
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            LanguageId = new Guid("c9dd8ea6-1e75-4b1f-b46c-4139cca92fc7"),
                            LanguageName = "Malay"
                        },
                        new
                        {
                            LanguageId = new Guid("52e09e8a-d41b-4194-be02-89bfb4b8215c"),
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageId = new Guid("42e5e507-309a-4683-976d-0e5532a14733"),
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageId = new Guid("13b58d17-9354-4a0f-bca3-6f7b2c755c00"),
                            LanguageName = "Maori"
                        },
                        new
                        {
                            LanguageId = new Guid("8e86e06d-0cc8-4a5f-bccd-25c7e16fde52"),
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageId = new Guid("54498ab3-6e05-4328-86b6-cd375bc27e02"),
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            LanguageId = new Guid("9775f6c5-d372-4550-9485-75645078d2da"),
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            LanguageId = new Guid("9e017720-f43d-4239-a8dd-6f44ecc1ba8b"),
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = new Guid("3e8f09b0-00a3-4435-938f-708e2ee61c43"),
                            LanguageName = "Odia"
                        },
                        new
                        {
                            LanguageId = new Guid("e60a1c88-d7e6-4098-9b94-93270e569d69"),
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            LanguageId = new Guid("98db9054-63e5-45e3-b9f5-83aadb48a4a8"),
                            LanguageName = "Persian"
                        },
                        new
                        {
                            LanguageId = new Guid("498bdced-826e-4efe-829a-fd4e71432eaa"),
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageId = new Guid("848a06a1-885d-45ba-a619-00b3c8b40e61"),
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("69783dab-c063-4a30-b4a2-06e0294a0214"),
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageId = new Guid("6152c714-257e-4e25-abb7-26b666545300"),
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageId = new Guid("9aa8b442-fcd8-4e7d-a29e-c88d727e289c"),
                            LanguageName = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("98ae6a01-c0ce-4315-a897-d6b2ca928b27"),
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            LanguageId = new Guid("86fb0b10-c6c7-4d08-8bd5-4452e52ed071"),
                            LanguageName = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = new Guid("e928f5e6-7cc5-4ac6-bd42-ee43a4806925"),
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            LanguageId = new Guid("cdb33986-58dc-41a6-8fb1-87ac304197d3"),
                            LanguageName = "Sesotho"
                        },
                        new
                        {
                            LanguageId = new Guid("ce021e6a-ecf0-4cc3-968a-e9ce29d0bd69"),
                            LanguageName = "Shona"
                        },
                        new
                        {
                            LanguageId = new Guid("8f9a8080-97a7-4bfd-82cf-138b9811a8ef"),
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            LanguageId = new Guid("6e4866ec-b5cb-48b1-813f-44d12003dd6c"),
                            LanguageName = "Sinhala"
                        },
                        new
                        {
                            LanguageId = new Guid("1394e7e8-793d-493c-b8d2-592f96e4c945"),
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageId = new Guid("06aa161d-9277-4c86-8065-fd7adf10237c"),
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageId = new Guid("5966a108-b4e1-4c76-99f3-05ac97399d35"),
                            LanguageName = "Somali"
                        },
                        new
                        {
                            LanguageId = new Guid("2e450857-63c3-4587-8d04-5001c6fd8e90"),
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("132d1aa3-829e-4a6a-8974-766787b9e588"),
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            LanguageId = new Guid("21b6ae01-99f3-470c-9171-a6e8b8a7190c"),
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            LanguageId = new Guid("d98c4a0d-d685-493b-b801-4dbfbe52196a"),
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = new Guid("353f5216-5b12-4cbc-8464-432c3427bccd"),
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("3133d4b7-6950-4e14-98bb-65262af726d9"),
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageId = new Guid("439a8cd7-979b-4431-998e-cfeb8c7bfff5"),
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            LanguageId = new Guid("91e285f8-a6a0-4620-bbf9-0e794674f71f"),
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageId = new Guid("7c03c40a-32ec-49b8-ad2e-a60c7ba56045"),
                            LanguageName = "Thai"
                        },
                        new
                        {
                            LanguageId = new Guid("2d4757ec-7e65-46b6-bef3-03228aa4051e"),
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            LanguageId = new Guid("6b667fd4-ca12-4c15-87f6-0dd0ec7ae3e2"),
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            LanguageId = new Guid("1d87bea1-2af3-49e5-87c4-beb9fa88e536"),
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("3cd8a407-ff6e-4e4b-b4af-98f47d7fdc5c"),
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageId = new Guid("ce532e9a-7b8a-435c-aead-fe6ac7e429f8"),
                            LanguageName = "Uyghur"
                        },
                        new
                        {
                            LanguageId = new Guid("e4f6cd69-e399-41dd-937d-6cddf4a1e6c8"),
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            LanguageId = new Guid("a8d00bfa-de07-4e2d-8b53-d6e8ad886412"),
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = new Guid("8997b74b-23c9-4398-a5a5-a1d795cd4b70"),
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            LanguageId = new Guid("704d13ee-b868-423d-b49b-39089a9bc155"),
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            LanguageId = new Guid("2781aa82-50ba-439f-b6bc-0cdf5979e875"),
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            LanguageId = new Guid("ae522746-270d-47eb-b1b4-f97820864818"),
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            LanguageId = new Guid("66b9afd4-4630-4ce8-8d78-4c766f18d9cd"),
                            LanguageName = "Zulu"
                        },
                        new
                        {
                            LanguageId = new Guid("5126d84e-754d-4b47-a3c2-35394160b1ab"),
                            LanguageName = "Dulegaya (Guna/Kuna)"
                        });
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Wishlist", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeopleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortStory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<string>("WishlistDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WishlistHeroImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WishlistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WishlistId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.WishlistDestination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WishlistDestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DestinationId", "WishlistId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistDestinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryDay", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Wishlist", "Wishlist")
                        .WithMany("ItineraryDays")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryItem", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.ItineraryDay", "ItineraryDay")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.WishlistDestination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("WishlistDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistDestinations")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Navigation("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");

                    b.Navigation("WishlistDestinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryDay", b =>
                {
                    b.Navigation("ItineraryItems");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Wishlist", b =>
                {
                    b.Navigation("ItineraryDays");

                    b.Navigation("WishlistDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
