// <auto-generated />
using System;
using Hodrac_MVP_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hodrac_MVP_Backend.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20260303130254_ChangeColumnNameDestinationTable")]
    partial class ChangeColumnNameDestinationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestPeriodToVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrencyId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("9cea29c8-c9bb-4e66-85bf-064fedf0de50"),
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = new Guid("8e1c6afb-b41f-4062-a8e7-323792ddc369"),
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            LanguageId = new Guid("9db8c8b1-1b93-4e2f-8699-a60ff2408752"),
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            LanguageId = new Guid("781eea72-1f53-414e-a88a-08c17918b491"),
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            LanguageId = new Guid("6680020d-5c55-44fa-927c-0ce2e9e4c150"),
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("ec55acb2-4813-4761-a49e-840409dee4d6"),
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            LanguageId = new Guid("d12237a5-5974-4e12-9029-5db6a9865439"),
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("c0db0962-3b7f-44f2-a11e-e98905a07099"),
                            LanguageName = "Basque"
                        },
                        new
                        {
                            LanguageId = new Guid("e8518743-141b-4594-a49d-cb2c5f00b1b7"),
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("81f2ef40-e6e3-4ba6-ae0a-838fcdf1b807"),
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            LanguageId = new Guid("d8d2cf79-d646-4fe9-ad50-10dad9a73f04"),
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            LanguageId = new Guid("e58dd784-911a-4555-ab8b-1451a7666109"),
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = new Guid("1a462be2-0a39-499a-8444-14c86b743b82"),
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            LanguageId = new Guid("261d75a5-2e19-4038-bdfd-6bafb9550dcf"),
                            LanguageName = "Catalan"
                        },
                        new
                        {
                            LanguageId = new Guid("1286232e-a894-4ec2-9d76-c82e9d7dc287"),
                            LanguageName = "Cebuano"
                        },
                        new
                        {
                            LanguageId = new Guid("fd3e882d-09d2-4cba-bcd3-c8c6a9a9beea"),
                            LanguageName = "Chichewa"
                        },
                        new
                        {
                            LanguageId = new Guid("62165eb5-f503-4a8f-9d12-671cb900b1ec"),
                            LanguageName = "Chinese (Mandarin)"
                        },
                        new
                        {
                            LanguageId = new Guid("288bec99-c596-4aac-ad16-4299180aae55"),
                            LanguageName = "Chinese (Cantonese)"
                        },
                        new
                        {
                            LanguageId = new Guid("64216d20-f8b6-480a-91b3-0d2440af7a29"),
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            LanguageId = new Guid("f862e80f-65a3-4f57-9afc-14274a223d5c"),
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageId = new Guid("6d835d54-8aee-484c-bbd3-b3d3c8cc6d4e"),
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageId = new Guid("84303e00-692e-477e-b6a6-a0c457c1d1d1"),
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageId = new Guid("fe9dac17-183b-486e-834c-709aba42d862"),
                            LanguageName = "Dari"
                        },
                        new
                        {
                            LanguageId = new Guid("e6d1bb19-62ad-43ec-841c-e7575a5ee095"),
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageId = new Guid("48f1904d-51ec-407e-86a2-914437418ba5"),
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("6ab5e21a-fe66-4ec9-8b24-1f5e21905a8c"),
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            LanguageId = new Guid("075cb1fc-35f8-4eec-8c1e-f17a4030588a"),
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageId = new Guid("ee1bd0b0-5b02-46b1-8199-e6a160af1f6e"),
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            LanguageId = new Guid("00f967f6-424e-436c-9d32-5c0cc9a52a01"),
                            LanguageName = "Filipino"
                        },
                        new
                        {
                            LanguageId = new Guid("56e64dd4-5ab0-4ee8-b7a3-8545a1d93642"),
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageId = new Guid("79b9aa1e-caec-4a69-bef1-57b82737ef73"),
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("fa613144-e46d-415c-832b-a02f7895411b"),
                            LanguageName = "Frisian"
                        },
                        new
                        {
                            LanguageId = new Guid("f5deb12c-c1bb-46e5-b3cf-b03ce236e973"),
                            LanguageName = "Galician"
                        },
                        new
                        {
                            LanguageId = new Guid("2e14aae0-22c3-499b-b867-8ffbe9b7f93e"),
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("45c62de4-ae02-4236-a8ad-f3522520909d"),
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("ac5ec9c4-64a4-474a-aa53-9798783cf24b"),
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageId = new Guid("bff36412-1881-4687-9700-fe121b7f47e3"),
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            LanguageId = new Guid("67637f69-fa8d-4819-bd58-8666f94d6d94"),
                            LanguageName = "Haitian Creole"
                        },
                        new
                        {
                            LanguageId = new Guid("cf2419e9-1ed0-4479-a66f-c63bb9477572"),
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            LanguageId = new Guid("aded6e60-d706-4a91-900c-9099d2c19c65"),
                            LanguageName = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = new Guid("9b283bfa-4800-4273-aa79-1035532d5a28"),
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            LanguageId = new Guid("01f7a57e-4c1c-4ef8-add1-bfa941f7df6f"),
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageId = new Guid("0466a3f5-6e9c-42c6-b9f3-5c031ae9f4fa"),
                            LanguageName = "Hmong"
                        },
                        new
                        {
                            LanguageId = new Guid("a9a61a43-59c2-44c6-83fa-abd556e6b254"),
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("738156d8-3524-4ddb-b36b-b2cc86bd3934"),
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            LanguageId = new Guid("0e91ed7c-9c18-4634-a279-b3c851a01dd3"),
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            LanguageId = new Guid("887dc96b-7101-4f30-9225-2eda57a58efa"),
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            LanguageId = new Guid("8e04a445-9a9d-4324-98f6-ac34172a83ce"),
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageId = new Guid("f5637473-43a8-4931-aa80-4dd90f5fbfe6"),
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("2bad1600-c649-45ec-b668-44cbcb0738b5"),
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("2bc4474d-8dd7-41e6-a69f-a0845c7bb420"),
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            LanguageId = new Guid("21c68a2e-08b4-41b0-803e-0f8eb4fb2310"),
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageId = new Guid("b76c845b-5943-4b68-91c8-6ba108d76bbf"),
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("fa68c758-2203-408e-8b79-27d9a632fd91"),
                            LanguageName = "Khmer"
                        },
                        new
                        {
                            LanguageId = new Guid("ba848ef2-d1f1-43ec-bdc9-e8f59ec7f8b6"),
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = new Guid("7d6f783f-370b-4104-9e7a-0b7df877cdaa"),
                            LanguageName = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("63a28ac1-c2ea-4a87-9998-6b2a3f0e249e"),
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            LanguageId = new Guid("df32aa66-efa2-4f3b-9a84-57f75818a980"),
                            LanguageName = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("dc37b733-574a-49ce-b8f3-c8c1c555661e"),
                            LanguageName = "Lao"
                        },
                        new
                        {
                            LanguageId = new Guid("62b47c02-e109-499f-9297-82bcfc975e93"),
                            LanguageName = "Latin"
                        },
                        new
                        {
                            LanguageId = new Guid("04ee5635-d9d9-4e2b-aad0-53216ffe32dd"),
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageId = new Guid("83e89686-2812-429f-9b43-ecb3d83ab8d8"),
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = new Guid("422c3e14-01c5-4ff1-961b-6f3ac937bf2f"),
                            LanguageName = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = new Guid("46673f6a-4e4e-41bd-a44e-79c1ea340d64"),
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            LanguageId = new Guid("535d7572-96fc-46a5-8e49-2b16d1541b42"),
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            LanguageId = new Guid("8dbad84a-5822-4acd-8c1e-f1b7b348200e"),
                            LanguageName = "Malay"
                        },
                        new
                        {
                            LanguageId = new Guid("fc60c2b5-1c53-4456-a901-53f180eec94c"),
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageId = new Guid("6e4c9568-b948-46c7-b196-16f77f88e493"),
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageId = new Guid("43072520-7822-40e9-81a0-9c1862143992"),
                            LanguageName = "Maori"
                        },
                        new
                        {
                            LanguageId = new Guid("e035133c-6159-4ac5-9872-3d6ced0eca09"),
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageId = new Guid("5e37b171-780f-45a8-a549-0f4b03a09fef"),
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            LanguageId = new Guid("23e3a5ca-0cd9-4bb9-b3e6-55c5ecd2f029"),
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            LanguageId = new Guid("15e9b725-1ac8-4d0f-bdfc-10332b2365b6"),
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = new Guid("c32796eb-21fb-4ceb-8207-de63256b9ae7"),
                            LanguageName = "Odia"
                        },
                        new
                        {
                            LanguageId = new Guid("0cfdc20f-d9cc-4cdc-8a27-8e8ceb000ca5"),
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            LanguageId = new Guid("28362a92-16f2-4f93-84f4-81a6d812d801"),
                            LanguageName = "Persian"
                        },
                        new
                        {
                            LanguageId = new Guid("cb42d190-e45d-46c9-a1bf-300daa6416a4"),
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageId = new Guid("8eb48d43-9f92-4a35-82aa-e82b152245dc"),
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("ece36603-4835-451f-8aeb-e67bc2d1795d"),
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageId = new Guid("39ecd4be-df00-4e5a-8515-77cf5b92c941"),
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageId = new Guid("7daa305a-3046-475d-8c15-a577e5b02232"),
                            LanguageName = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("7595c6ab-f2a1-4473-8747-09aacc531aaa"),
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            LanguageId = new Guid("fde97d98-2613-4890-b250-0edae7ce886a"),
                            LanguageName = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = new Guid("726ef67b-1308-4e1d-8cf1-cb2160796390"),
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            LanguageId = new Guid("5f9dc675-02a8-4ec4-8573-b5b68597ae9d"),
                            LanguageName = "Sesotho"
                        },
                        new
                        {
                            LanguageId = new Guid("e6454b51-85ac-4d70-84a3-a490c866d2bb"),
                            LanguageName = "Shona"
                        },
                        new
                        {
                            LanguageId = new Guid("8d5eeb05-6bd6-4f2b-9613-2c118aa0c4c1"),
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            LanguageId = new Guid("acb1b412-6ed7-40c8-8f27-2378ddc20fe6"),
                            LanguageName = "Sinhala"
                        },
                        new
                        {
                            LanguageId = new Guid("342bf720-9175-479f-b7e7-05faf719785b"),
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageId = new Guid("f9bdd2a1-ec8f-4420-bd56-9e11b057be09"),
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageId = new Guid("dd6b6b75-b612-4089-a4e7-5d9d4ec57f6d"),
                            LanguageName = "Somali"
                        },
                        new
                        {
                            LanguageId = new Guid("1693c863-b2ae-4c25-ad05-c71ba870ab4a"),
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("ac12fc21-88aa-4d56-9f91-cc9ea4266c3b"),
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            LanguageId = new Guid("f250868e-c0c2-4b08-be88-7ca71b2b213a"),
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            LanguageId = new Guid("af4a2181-2ab0-43f5-8d0c-e05790fadae0"),
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = new Guid("b6e0b74b-5d6b-4dda-9f41-24015973f8e2"),
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("b484f1d6-9b6e-4962-8a4b-90b20372fdfe"),
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageId = new Guid("5e65d6fe-8396-4123-9532-2874f7ccef12"),
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            LanguageId = new Guid("26438d9a-a1a8-46b7-ba60-545a0da663c6"),
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageId = new Guid("51daa74c-d120-4b1a-aef1-8a6d0c281ecf"),
                            LanguageName = "Thai"
                        },
                        new
                        {
                            LanguageId = new Guid("4899b0f5-3215-4ca4-8afa-f3df489498e1"),
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            LanguageId = new Guid("539981ea-1b15-4dfd-8b9b-8770abbf6b4b"),
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            LanguageId = new Guid("6eac0906-0c01-48be-b0a7-c83efd5cdea0"),
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("1b9867af-2a86-4937-a3e7-484892d36fa1"),
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageId = new Guid("1f640346-eaf5-4f7a-8378-05cab21f784b"),
                            LanguageName = "Uyghur"
                        },
                        new
                        {
                            LanguageId = new Guid("658131aa-b29f-4e20-bf80-983225aa77f4"),
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            LanguageId = new Guid("17b6f561-277b-49b9-a4e4-d585173cf6a3"),
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = new Guid("1086c2e3-7446-4fde-9154-275634f273f9"),
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            LanguageId = new Guid("ef53bda6-366a-4d96-82dd-c8dd2876093f"),
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            LanguageId = new Guid("6cb432ff-e209-4dae-86b8-b1f818c757de"),
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            LanguageId = new Guid("fdcdefd5-b58e-48be-b063-1b3ade8f8e7a"),
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            LanguageId = new Guid("fb8ef6f8-c7ec-4da6-af37-24f7107fec2e"),
                            LanguageName = "Zulu"
                        });
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Navigation("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });
#pragma warning restore 612, 618
        }
    }
}
