// <auto-generated />
using System;
using Hodrac_MVP_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hodrac_MVP_Backend.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20260304200932_ChangeColumnDatatypeChangeDestinationTable")]
    partial class ChangeColumnDatatypeChangeDestinationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestPeriodToVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCost")
                        .HasColumnType("int");

                    b.Property<int>("MinCost")
                        .HasColumnType("int");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrencyId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("895aaa65-0bdd-47e7-a317-c181c0b03932"),
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = new Guid("322ebf3d-436e-475e-96c0-1ab491aad29c"),
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            LanguageId = new Guid("b4f62ccb-1b86-4583-b27f-15ad317c5161"),
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            LanguageId = new Guid("4deb3b54-996b-4327-a122-1e011174dcfb"),
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            LanguageId = new Guid("f2ec41a5-3479-4c85-bc7f-e6259d4b4b4b"),
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("46e12d33-cc3c-4f94-aee1-22ca7e3cdeba"),
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            LanguageId = new Guid("6bf6972e-55ac-48a8-b098-fb4596b381f5"),
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("2b19ceb5-a8b4-4d7d-be33-264756f02377"),
                            LanguageName = "Basque"
                        },
                        new
                        {
                            LanguageId = new Guid("11727a4b-2e2d-44f3-82d3-250ea29a986f"),
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("ae5dc924-7b67-4c3c-b53f-f82359eaec31"),
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            LanguageId = new Guid("dd46c9af-2683-4c4f-b109-62892d9271a8"),
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            LanguageId = new Guid("9fe6c781-153d-4a5a-89f4-cacf84e1e325"),
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = new Guid("d507f872-0bb1-4da6-b1fd-3a44f873770e"),
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            LanguageId = new Guid("51d90d54-1e7a-405a-8f58-2517dd4d3a60"),
                            LanguageName = "Catalan"
                        },
                        new
                        {
                            LanguageId = new Guid("1013b2fa-a436-4a91-b1c7-c486a909a57a"),
                            LanguageName = "Cebuano"
                        },
                        new
                        {
                            LanguageId = new Guid("37fbee5b-6a40-4f90-a3a4-8d6ee7ec5f31"),
                            LanguageName = "Chichewa"
                        },
                        new
                        {
                            LanguageId = new Guid("1922f2d2-5142-4ffc-8585-a36d4898567f"),
                            LanguageName = "Chinese (Mandarin)"
                        },
                        new
                        {
                            LanguageId = new Guid("38bde745-0954-448a-a74e-acf6db3dbdee"),
                            LanguageName = "Chinese (Cantonese)"
                        },
                        new
                        {
                            LanguageId = new Guid("e88c1709-72d1-480e-bd63-51f221c7e158"),
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            LanguageId = new Guid("e2da02f4-d6cd-412c-af65-22ec92c0cfc0"),
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageId = new Guid("8c8773ce-cfe1-458f-ba08-d199bd0f94ed"),
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageId = new Guid("abfc1249-06ed-442f-b3df-2afaf47af3fb"),
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageId = new Guid("c178da8c-eb5b-4807-a5ea-c5ae499ffac3"),
                            LanguageName = "Dari"
                        },
                        new
                        {
                            LanguageId = new Guid("610b4324-c48f-48fe-8ccc-b058eaacb55e"),
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageId = new Guid("6d0d3a9e-852c-431c-a213-e4d81fc30927"),
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("216a8879-448d-4df1-ad2a-e32117b98df5"),
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            LanguageId = new Guid("44d95055-91cb-465d-982e-1dcb6f730599"),
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageId = new Guid("87bccce0-912e-41d3-b5d0-b6bcccdff8f8"),
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            LanguageId = new Guid("79e904eb-95cb-4865-896e-80fa32219f20"),
                            LanguageName = "Filipino"
                        },
                        new
                        {
                            LanguageId = new Guid("133d312e-25ed-4225-8fa2-791e2caaf924"),
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageId = new Guid("1e0d0333-2389-4321-9e07-dca4adfcb793"),
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("9cb6b819-445e-4bc1-9b7d-0367584af30f"),
                            LanguageName = "Frisian"
                        },
                        new
                        {
                            LanguageId = new Guid("86d5af9c-f183-406e-b2b0-a289ca8772ae"),
                            LanguageName = "Galician"
                        },
                        new
                        {
                            LanguageId = new Guid("46081112-8792-4d2e-9bdc-b360180c7206"),
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("c22d44d4-1271-41e2-aa88-2a71d47dbf7d"),
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("b1f35226-8059-46f6-b8ed-799c5081e123"),
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageId = new Guid("7b81d968-6c16-4b09-bd02-225ec480e808"),
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            LanguageId = new Guid("18df9d80-6380-465f-8040-11bb347ef9b6"),
                            LanguageName = "Haitian Creole"
                        },
                        new
                        {
                            LanguageId = new Guid("884abc58-e708-4c6d-be75-f885dafef972"),
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            LanguageId = new Guid("3d53315b-655b-48c4-a33d-6c396d7d08f6"),
                            LanguageName = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = new Guid("1421c96c-539f-4037-bb23-3deb4a630a22"),
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            LanguageId = new Guid("92f79cdf-6fa9-42be-bccf-28843354a4b5"),
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageId = new Guid("8ac1b5a6-d729-4aa7-bbd0-590b12f63842"),
                            LanguageName = "Hmong"
                        },
                        new
                        {
                            LanguageId = new Guid("b946ffc2-56fb-4330-8616-879c8a2b2828"),
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("babffc95-11d7-4d2f-9b4c-71a4986384c4"),
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            LanguageId = new Guid("c6f4026b-ff47-4af8-809f-320bace1f9b5"),
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            LanguageId = new Guid("d3bf0282-6f0e-48b9-b0f9-d188936e884c"),
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            LanguageId = new Guid("a0ab2f14-bd35-44ed-ae62-285413ef5002"),
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageId = new Guid("39703518-291c-43b2-b235-2d1be502bb50"),
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("beec7a65-89b9-4d0b-8dcb-5f374ab1d5ea"),
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("469bd6df-8448-4c0e-a6df-167794dd8991"),
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            LanguageId = new Guid("f2ad7858-5eec-4c81-ab27-b7d2cbc74c57"),
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageId = new Guid("db4e9518-6b7b-465b-a9f1-987249875a7a"),
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("e1a690dd-1bd8-4fba-8356-a77ce8284a3a"),
                            LanguageName = "Khmer"
                        },
                        new
                        {
                            LanguageId = new Guid("eba06242-3de5-47cd-ba3a-c362212d3399"),
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = new Guid("ec6e1516-168f-4cc9-9a0e-1791c4c826f0"),
                            LanguageName = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("7f8cffa4-23e8-48d8-b0af-4793f90f7130"),
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            LanguageId = new Guid("940cda64-a29f-4255-ab31-e4b54a4860e0"),
                            LanguageName = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("174c8433-c8f5-4664-ac63-baf764dd4ed1"),
                            LanguageName = "Lao"
                        },
                        new
                        {
                            LanguageId = new Guid("030dc92d-8107-4c6e-932a-4c224e45a0df"),
                            LanguageName = "Latin"
                        },
                        new
                        {
                            LanguageId = new Guid("ca46f395-6b91-4b10-88df-a0a088548e8d"),
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageId = new Guid("9a8c2a19-7272-4d3b-9733-c28b446ba09c"),
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = new Guid("7ccccdba-12d8-48ca-b786-30b63147ac52"),
                            LanguageName = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = new Guid("3991ba11-4221-4e04-a9b3-12d920abec9f"),
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            LanguageId = new Guid("918973c9-1c25-4d6e-8835-5b7b4cc65f0e"),
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            LanguageId = new Guid("ec878212-957d-42c7-bd7c-f459449d519b"),
                            LanguageName = "Malay"
                        },
                        new
                        {
                            LanguageId = new Guid("1feebf54-ff9f-48b4-9373-4186ab47d3b8"),
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageId = new Guid("99c51b92-3def-4200-9201-02bb31bbd7d1"),
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageId = new Guid("380e1bd0-8ef8-4ebc-a2d1-3f2e4f50dae3"),
                            LanguageName = "Maori"
                        },
                        new
                        {
                            LanguageId = new Guid("2e772a06-ecaa-44eb-ab78-c352e2b906dd"),
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageId = new Guid("dc6ab444-fe4e-432a-8463-6f8bcb160fb7"),
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            LanguageId = new Guid("bef6e44c-34e0-44ad-b3c0-b3fb82eb6984"),
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            LanguageId = new Guid("15858194-269d-45ef-9c8e-fbb09286cc45"),
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = new Guid("e72fd9ec-432f-45b6-8c90-93ebdf65de5b"),
                            LanguageName = "Odia"
                        },
                        new
                        {
                            LanguageId = new Guid("cac59d32-8bc5-44e0-8182-51a5f31156e5"),
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            LanguageId = new Guid("feca7294-9eaf-4b0e-869d-9e39c5f016e3"),
                            LanguageName = "Persian"
                        },
                        new
                        {
                            LanguageId = new Guid("e3d4c002-71c4-4440-9e49-15032bf95a4d"),
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageId = new Guid("cea0dcf4-c3ef-4660-9a0a-870c69a90591"),
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("099da564-d608-4ae5-8364-e4d651da3d81"),
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageId = new Guid("1c4e3bbb-ae91-4712-b506-9eb785f82970"),
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageId = new Guid("81dcbfdf-1f39-4156-bf91-b6fa61d0a262"),
                            LanguageName = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("5dbd48d0-098b-4aec-8603-21c62ce47f07"),
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            LanguageId = new Guid("112b7da3-5e14-4e9c-bfbc-9c5f7605b58c"),
                            LanguageName = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = new Guid("fc70096f-b601-49a6-bba1-5408235f82f2"),
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            LanguageId = new Guid("8a9cbfdb-3e46-40f0-9fe4-845c11467ea9"),
                            LanguageName = "Sesotho"
                        },
                        new
                        {
                            LanguageId = new Guid("7b487a84-ebbf-44f5-a520-d04192bd82ac"),
                            LanguageName = "Shona"
                        },
                        new
                        {
                            LanguageId = new Guid("d1933916-6dfb-4111-aff3-45747a01ebce"),
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            LanguageId = new Guid("40403d14-4311-48e3-9042-bdd3b6f3140a"),
                            LanguageName = "Sinhala"
                        },
                        new
                        {
                            LanguageId = new Guid("c2b40788-9e3a-4924-b2d0-a0598445552a"),
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageId = new Guid("7a885749-ec02-4a6b-8207-d3ea8599bf3b"),
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageId = new Guid("75ea9925-ddb5-465f-90cc-4c416177ac4d"),
                            LanguageName = "Somali"
                        },
                        new
                        {
                            LanguageId = new Guid("82018758-ff37-421e-b824-a1f812c7283c"),
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("03543b98-1d09-48b9-869a-bcee9c1beab8"),
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            LanguageId = new Guid("0a5e1099-4b6b-4f97-a206-8b9295ab2111"),
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            LanguageId = new Guid("e082d48e-6f9e-459b-927f-8cd73daa78bf"),
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = new Guid("27cd0e91-c9ff-40dd-83e4-659e056057e4"),
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("7c5bcb18-7997-4667-b789-60ba11b38200"),
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageId = new Guid("7703f728-1271-44d5-8d12-a8a810d23790"),
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            LanguageId = new Guid("41d05820-34de-4649-8847-ffcaafd5ba1d"),
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageId = new Guid("0526b07c-b64c-46e7-8395-9de167829684"),
                            LanguageName = "Thai"
                        },
                        new
                        {
                            LanguageId = new Guid("70a2798e-4c4a-481d-aa66-1e336578a2a8"),
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            LanguageId = new Guid("aa8ccc7e-c49b-4f55-bc3a-1197a496576c"),
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            LanguageId = new Guid("92999e6f-21e5-4fdd-a57d-355670be4cd3"),
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("efe640c5-1553-40c0-bd83-2ea283653adb"),
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageId = new Guid("cbb981d2-6f69-450a-b419-e38b44bd728a"),
                            LanguageName = "Uyghur"
                        },
                        new
                        {
                            LanguageId = new Guid("2bd74c82-0073-4330-8de2-fadeaebdcda8"),
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            LanguageId = new Guid("5c8a9c03-fcfc-4f68-8909-91f657401712"),
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = new Guid("e5b28ea1-adcf-4576-bb11-e7712d4b0413"),
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            LanguageId = new Guid("086c7a41-402e-4f8b-b1e8-c73b32c7ea8f"),
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            LanguageId = new Guid("bac69883-65a5-43af-99a6-463a7812269a"),
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            LanguageId = new Guid("0b57ec53-4f6c-4c5a-8a95-edaf0036b21a"),
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            LanguageId = new Guid("7555567d-0a28-4c17-9e60-73fb62e1153b"),
                            LanguageName = "Zulu"
                        });
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Navigation("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });
#pragma warning restore 612, 618
        }
    }
}
