// <auto-generated />
using System;
using Hodrac_MVP_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hodrac_MVP_Backend.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20260413071849_WishlistHeroImage")]
    partial class WishlistHeroImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestPeriodToVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCost")
                        .HasColumnType("int");

                    b.Property<int>("MinCost")
                        .HasColumnType("int");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrencyId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryDay", b =>
                {
                    b.Property<Guid>("ItineraryDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("DayTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItineraryDayId");

                    b.HasIndex("WishlistId");

                    b.ToTable("ItineraryDays");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryItem", b =>
                {
                    b.Property<Guid>("ItineraryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemOrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItineraryItemId");

                    b.HasIndex("ItineraryDayId");

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("abfc2ae1-25ba-40a8-91f5-5fcad6f80197"),
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = new Guid("c117fcdb-ca23-404b-b026-b029c4e2c146"),
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            LanguageId = new Guid("d6ee6956-c8dd-4248-8ce4-c3f0c9fe6530"),
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            LanguageId = new Guid("c4eb04a2-6061-4012-a829-eb936f3a6314"),
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            LanguageId = new Guid("4741846f-3332-4f1c-89e3-cbadefeb10e8"),
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("1c6519f6-9758-4d42-9f6c-c9dc0d4e10eb"),
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            LanguageId = new Guid("63271a22-d9ad-4c3c-9caa-a3374bd1a309"),
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("31e8c664-4999-41c8-a0af-db74d2a40d31"),
                            LanguageName = "Basque"
                        },
                        new
                        {
                            LanguageId = new Guid("ebe39f0f-ade1-407f-99f3-bd940632d332"),
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("aac5fe8a-9937-482b-9d59-9f8a62fe1738"),
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            LanguageId = new Guid("aacaedd6-ce0f-45bb-9718-aa62e954a6b8"),
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            LanguageId = new Guid("9b831981-22d1-4729-88df-c25f7f8da4f3"),
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = new Guid("fba60cff-2eda-4efa-99c9-67e737e3a69e"),
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            LanguageId = new Guid("40d8de17-b330-4054-8740-ccec05a59c8a"),
                            LanguageName = "Catalan"
                        },
                        new
                        {
                            LanguageId = new Guid("16245538-3939-4dce-adae-df148f60f4ed"),
                            LanguageName = "Cebuano"
                        },
                        new
                        {
                            LanguageId = new Guid("4d4a04c3-f6aa-49e9-9e34-e6b9b43340a3"),
                            LanguageName = "Chichewa"
                        },
                        new
                        {
                            LanguageId = new Guid("8996315b-ec3c-4fc7-9f56-d29e4361d667"),
                            LanguageName = "Chinese (Mandarin)"
                        },
                        new
                        {
                            LanguageId = new Guid("14020c74-12fa-4b4b-8d12-aa249dd46bba"),
                            LanguageName = "Chinese (Cantonese)"
                        },
                        new
                        {
                            LanguageId = new Guid("94722051-e2cd-4094-a771-1bd83e577ee7"),
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            LanguageId = new Guid("61090b74-66d8-4145-b5cd-61ed9c608904"),
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageId = new Guid("d7f53618-9a0a-4581-b26f-bd292852f0cf"),
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageId = new Guid("8138c66b-dfe0-4784-9a4a-f5dd1a381837"),
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageId = new Guid("f59d713d-7d4f-4b66-b853-0c3d89242023"),
                            LanguageName = "Dari"
                        },
                        new
                        {
                            LanguageId = new Guid("259e4ac5-ac27-46b2-b5c0-23b67f6c18c7"),
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageId = new Guid("cf1ddd05-0ee6-41d6-861d-20ec796007aa"),
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("54ee87e7-344b-4978-937d-efd284cb63c1"),
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            LanguageId = new Guid("71ae9f50-765e-4c59-b202-0a8a57639b50"),
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageId = new Guid("894dd2ad-6df7-4f88-9690-3e8d729a3910"),
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            LanguageId = new Guid("128ea88d-e614-42a1-86e5-acfd952c5abc"),
                            LanguageName = "Filipino"
                        },
                        new
                        {
                            LanguageId = new Guid("284dace6-7160-411d-84b3-b6a060d5b30a"),
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageId = new Guid("53d7d7f5-7438-4a5d-a86d-55e6ff66cd2f"),
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("58efcfb8-db7e-4658-a2f4-8987d5f9322c"),
                            LanguageName = "Frisian"
                        },
                        new
                        {
                            LanguageId = new Guid("89ec8ca9-a2e0-415b-9db2-61bb2333ac89"),
                            LanguageName = "Galician"
                        },
                        new
                        {
                            LanguageId = new Guid("36455568-b7f6-40ac-bcaa-1baa81be5fbf"),
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("f24cc0ca-3baa-4cfd-8c3d-13a08d793f30"),
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("46dcffda-1628-43dd-9041-9b2e8d2110d4"),
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageId = new Guid("6ab462de-1541-4e4c-8f6b-01aac6503913"),
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            LanguageId = new Guid("a0e5abee-71ec-42af-89c9-2a885f74da86"),
                            LanguageName = "Haitian Creole"
                        },
                        new
                        {
                            LanguageId = new Guid("4f0fc9aa-86dc-40ce-9309-49b54746b90a"),
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            LanguageId = new Guid("e0ee6b7e-6f43-4dd8-b0bc-c716be03f0ac"),
                            LanguageName = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = new Guid("cc7e6808-e632-47c8-9fbd-976709581898"),
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            LanguageId = new Guid("7672fad4-7f5a-4fad-aeae-79a10f7dd860"),
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageId = new Guid("c32ccfc6-cfae-4d17-81b5-6d5c22449698"),
                            LanguageName = "Hmong"
                        },
                        new
                        {
                            LanguageId = new Guid("82f463fd-9665-4fc4-ad99-59674019dfc8"),
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("1821beda-6668-4f4d-9878-8a64e744e18e"),
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            LanguageId = new Guid("fbf84766-a6f0-410a-aea1-ac8a47300aeb"),
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            LanguageId = new Guid("f3081008-a619-44ba-905b-b80fc97ee73b"),
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            LanguageId = new Guid("35066c36-044a-4dcf-b5e2-fe1ebbc68f33"),
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageId = new Guid("6dd574dc-bb88-4b83-9df0-7bf8074474cf"),
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("300a4757-0839-47ed-895b-6fb9734e0211"),
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("e9cf38e2-e8ea-453d-8f6c-a516fd1e872c"),
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            LanguageId = new Guid("fac9db25-e215-4a22-a558-c88a5b7a3b61"),
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageId = new Guid("ff3cdfa9-2acd-421b-8878-cc213ab163c9"),
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("0a28200e-01df-47c9-8487-828448696845"),
                            LanguageName = "Khmer"
                        },
                        new
                        {
                            LanguageId = new Guid("da6c5e1a-149e-4f97-a631-a30fb6e3a826"),
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = new Guid("83c10ca2-2f23-4155-a40f-a575e4e323d4"),
                            LanguageName = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("d8ab0770-aa56-4350-a15f-0ff160bb89e0"),
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            LanguageId = new Guid("6aeb1511-4275-4ec9-b40e-b5ef9c1f55af"),
                            LanguageName = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("da24b488-a0ec-4647-9228-222c1713d665"),
                            LanguageName = "Lao"
                        },
                        new
                        {
                            LanguageId = new Guid("f367c386-55cd-4bc9-8a3f-7ef47fe2e0ae"),
                            LanguageName = "Latin"
                        },
                        new
                        {
                            LanguageId = new Guid("bb039cd8-77b6-4cb0-84d4-61f7b25e112e"),
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageId = new Guid("bf03651a-4479-4a5a-b573-5d0eba16f961"),
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = new Guid("d1b3ee66-1d15-445b-a51a-51cb3b8fee2f"),
                            LanguageName = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = new Guid("3700af44-e6be-4163-9303-e04a0ddb8db7"),
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            LanguageId = new Guid("b78c73ba-47f8-4fc6-879b-f415081e7e3c"),
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            LanguageId = new Guid("8113357c-f78e-4dd6-9296-8654528251fa"),
                            LanguageName = "Malay"
                        },
                        new
                        {
                            LanguageId = new Guid("ca42d8b0-b326-4061-9d65-9e2dae5da8b8"),
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageId = new Guid("79d327b4-8ff4-485a-9538-e0ab5012c78a"),
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageId = new Guid("f43c82c0-c469-45ca-b2c3-a0b362c69c20"),
                            LanguageName = "Maori"
                        },
                        new
                        {
                            LanguageId = new Guid("c302d764-365e-428b-88b9-c1894622cf63"),
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageId = new Guid("e8087f8a-b1fb-4ff7-8d81-67e2ebc55ce1"),
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            LanguageId = new Guid("d00a9a2a-c4d4-4e8e-a753-256dc0cfdcf4"),
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            LanguageId = new Guid("8875cd38-d835-4979-8d83-e60b5bc8f19a"),
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = new Guid("e921ff2a-dff5-4782-a384-baca339632dc"),
                            LanguageName = "Odia"
                        },
                        new
                        {
                            LanguageId = new Guid("98394c66-df9d-4122-86fb-b7599ac6852c"),
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            LanguageId = new Guid("604a04c3-8842-41b4-8b10-33062fed0fbc"),
                            LanguageName = "Persian"
                        },
                        new
                        {
                            LanguageId = new Guid("45b2954e-d94c-4500-a8a0-7f8f15fc0ebe"),
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageId = new Guid("743ad1d2-b30e-4864-a381-c48fb90b088e"),
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("87da4109-865b-40ae-be65-9882fcaccf55"),
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageId = new Guid("ab95c78b-15d0-43cc-a7ea-4efb741b703c"),
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageId = new Guid("032a1ea8-f92e-4a65-a93b-0a8dd33817be"),
                            LanguageName = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("e7344872-a52a-409e-af41-1eea7ee16991"),
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            LanguageId = new Guid("392d9fdc-04a2-4617-9610-439dbd1270c8"),
                            LanguageName = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = new Guid("c31c7165-5631-4187-941d-9dbc31393e2e"),
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            LanguageId = new Guid("f3ec80cb-7977-4ae6-b1f7-c2994156515b"),
                            LanguageName = "Sesotho"
                        },
                        new
                        {
                            LanguageId = new Guid("d383966f-f3aa-4125-86df-05d0c92385cf"),
                            LanguageName = "Shona"
                        },
                        new
                        {
                            LanguageId = new Guid("ae5fadba-00b8-49bb-b9ee-5cb1cf99669e"),
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            LanguageId = new Guid("046a7ca0-fc58-4826-a93e-36c5b83a0b9d"),
                            LanguageName = "Sinhala"
                        },
                        new
                        {
                            LanguageId = new Guid("100a78c9-bc54-48d1-8dd8-365d94bb9b02"),
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageId = new Guid("03dba1c9-f4be-4cfd-9212-4547546c9055"),
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageId = new Guid("95e01111-e2e4-4da5-b99a-8dffc2a4f36a"),
                            LanguageName = "Somali"
                        },
                        new
                        {
                            LanguageId = new Guid("b9828a8e-2486-422a-9574-865ed5a3ee26"),
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("5c533dec-33fa-4e30-8b86-572fa467e3e9"),
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            LanguageId = new Guid("e2e1e9f4-23ee-4c06-add8-ee0582389ba4"),
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            LanguageId = new Guid("a87c7ecc-80f6-4ee5-8b74-2370fdd4a670"),
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = new Guid("3f64f189-594b-4392-9c5a-f48cab803e3e"),
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("81d98f1e-6c09-4e9d-9352-374bf925f1ee"),
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageId = new Guid("91dced94-04c1-4074-be42-12beef30cc1d"),
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            LanguageId = new Guid("022e3beb-01c9-4251-b99a-6a6999a2bc50"),
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageId = new Guid("bf38be2b-6e60-4ee4-b46a-c04e2db14027"),
                            LanguageName = "Thai"
                        },
                        new
                        {
                            LanguageId = new Guid("a04b61fb-57ab-422c-a1a4-6a2c4aa8eda0"),
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            LanguageId = new Guid("f808d107-50dc-4bd2-9fb9-fc849aff7211"),
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            LanguageId = new Guid("a1e1378f-9741-435e-a2c1-72cfa604e697"),
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("bd65de11-25f9-447a-b86a-4f1091eb73c1"),
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageId = new Guid("0181d6b0-55ec-4036-9912-b9319ebbc578"),
                            LanguageName = "Uyghur"
                        },
                        new
                        {
                            LanguageId = new Guid("552db47d-261b-41ff-ba7f-67156a08e19a"),
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            LanguageId = new Guid("0d9ad495-54c4-4613-a1ed-165303edf062"),
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = new Guid("d78cf70e-f41a-4617-96c1-849a0b71865c"),
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            LanguageId = new Guid("fbc7d791-0d9f-472c-92d3-f27533150692"),
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            LanguageId = new Guid("2536bf37-b5dd-4c53-87f0-1771e2730d11"),
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            LanguageId = new Guid("c8ff0dca-1466-4b38-8e00-b461bd810b64"),
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            LanguageId = new Guid("7277e28a-4904-4dd2-8f78-4f678e45be92"),
                            LanguageName = "Zulu"
                        });
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Wishlist", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeopleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortStory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<string>("WishlistDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WishlistHeroImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WishlistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WishlistId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.WishlistDestination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WishlistDestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DestinationId", "WishlistId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistDestinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryDay", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Wishlist", "Wishlist")
                        .WithMany("ItineraryDays")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryItem", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.ItineraryDay", "ItineraryDay")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.WishlistDestination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("WishlistDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistDestinations")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Navigation("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");

                    b.Navigation("WishlistDestinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.ItineraryDay", b =>
                {
                    b.Navigation("ItineraryItems");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Wishlist", b =>
                {
                    b.Navigation("ItineraryDays");

                    b.Navigation("WishlistDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
