// <auto-generated />
using System;
using Hodrac_MVP_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hodrac_MVP_Backend.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20260225144315_DestinationTableChangeTravelPeriodDataType")]
    partial class DestinationTableChangeTravelPeriodDataType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestPeriodToVist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrencyId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("3e1f00d2-0433-4f59-9c21-5c9106adc2b5"),
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = new Guid("7afdb2bd-39b1-49c8-8f5d-56322a561490"),
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            LanguageId = new Guid("c9c4c856-44fa-4e1a-9cdb-3ce7512fe17e"),
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            LanguageId = new Guid("15fdaeb6-0efd-4631-aa63-eaff2becd044"),
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            LanguageId = new Guid("8e12c0ad-b3cb-4335-a60a-ee1c9e2f62df"),
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("81b7478f-49a3-4441-bcf9-cbe5c22bbd54"),
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            LanguageId = new Guid("22c1a5ab-baba-4dc6-b3ed-03a7e575ba18"),
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("340082ed-9728-49f6-b22c-eba5fc5c64e9"),
                            LanguageName = "Basque"
                        },
                        new
                        {
                            LanguageId = new Guid("8eb626ed-52d2-4755-9d4d-35bf0f6a8939"),
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("1597a927-0925-4aae-87a2-0d776bc8d746"),
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            LanguageId = new Guid("a3a597e6-e5ba-41ff-a989-b8a118599237"),
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            LanguageId = new Guid("f7cd55f6-08ce-49a3-9272-d21d33d2d81c"),
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = new Guid("b3f47480-a1f1-4810-a3d1-15e0ae6cc4ca"),
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            LanguageId = new Guid("2b020151-9f32-4e6d-810b-ebd000c113ce"),
                            LanguageName = "Catalan"
                        },
                        new
                        {
                            LanguageId = new Guid("bb5773bf-29dd-4f27-b581-468909cdf6b6"),
                            LanguageName = "Cebuano"
                        },
                        new
                        {
                            LanguageId = new Guid("8beedab5-6ad1-4e60-a2aa-ab3373046b97"),
                            LanguageName = "Chichewa"
                        },
                        new
                        {
                            LanguageId = new Guid("8e82650c-8015-4731-b3b8-e713d9414bb5"),
                            LanguageName = "Chinese (Mandarin)"
                        },
                        new
                        {
                            LanguageId = new Guid("b2b1e566-49d0-4d7e-928b-07348b89eb6e"),
                            LanguageName = "Chinese (Cantonese)"
                        },
                        new
                        {
                            LanguageId = new Guid("7ae5dad7-65a9-4852-92ea-014804c6e747"),
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            LanguageId = new Guid("02462064-ae2a-405d-89b6-bd195b8efc37"),
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageId = new Guid("59e3bd95-f72a-443d-9072-ff27373d28ac"),
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageId = new Guid("5a625ea1-49fb-4ad0-bd0d-c503b855f3c9"),
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageId = new Guid("57417934-4755-4659-8a1b-012da47c57af"),
                            LanguageName = "Dari"
                        },
                        new
                        {
                            LanguageId = new Guid("d89dc7e4-5c6f-4e1c-895f-9fb8fb4d3dfc"),
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageId = new Guid("17356f78-a7e0-493b-ad4f-3117ecc1afc5"),
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("776d9508-283b-4756-8dc7-d2689d8c7846"),
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            LanguageId = new Guid("219788cd-6ce2-487c-83e5-c4d87026cad7"),
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageId = new Guid("2c486850-26f8-41fd-b99c-f693f9b15c81"),
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            LanguageId = new Guid("eee36b13-5490-405a-a744-23a0aebdab28"),
                            LanguageName = "Filipino"
                        },
                        new
                        {
                            LanguageId = new Guid("a48e9102-928b-4331-98f6-5c8fd072e216"),
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageId = new Guid("40818304-b73f-464d-8080-dbc0b1f39261"),
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("81ce8f4f-d0e3-4cb1-8457-b1dd44fb1c30"),
                            LanguageName = "Frisian"
                        },
                        new
                        {
                            LanguageId = new Guid("ade2b584-31e7-4c2b-bb13-f8f45ed6a306"),
                            LanguageName = "Galician"
                        },
                        new
                        {
                            LanguageId = new Guid("46b5b435-0540-4c14-a4dd-3dfe1a8cfde9"),
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("90485dea-a956-44c3-a7d1-cf64e8558cb2"),
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("c057f2b5-6274-4e45-8346-7cba222e058c"),
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageId = new Guid("1bc0e113-76ee-4f7a-81d2-20a5f6cab5ea"),
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            LanguageId = new Guid("9a814444-31a7-41c5-bf74-a60bdfa2bce2"),
                            LanguageName = "Haitian Creole"
                        },
                        new
                        {
                            LanguageId = new Guid("1d360ace-84db-4db8-956d-f589f18ecfab"),
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            LanguageId = new Guid("f8a11967-5b0e-4f98-b878-d27d48e8490a"),
                            LanguageName = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = new Guid("d63e0135-2084-477d-b6b4-eadac9d97640"),
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            LanguageId = new Guid("26544c08-2c74-4815-bfd5-e31a2ca8f1c3"),
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageId = new Guid("151168f3-e3bc-499c-8bcd-e9eb6626710c"),
                            LanguageName = "Hmong"
                        },
                        new
                        {
                            LanguageId = new Guid("7f6bba19-f418-4493-8ae8-6a8d8676aff7"),
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("6f768d6f-8692-4e57-bb81-42a922d4c54a"),
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            LanguageId = new Guid("21fde1d7-b00b-4fd3-ad54-b2d0890d9ca1"),
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            LanguageId = new Guid("59d25789-d3a2-49f1-acb8-b1e14e0279a3"),
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            LanguageId = new Guid("2a782769-6341-45f8-b3f8-3f6cfbf369d5"),
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageId = new Guid("261e5073-fdb1-4d89-a4ef-4717f9e8ece4"),
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("c859e37a-2779-439c-a7b5-e1f4922a3130"),
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("16a204f6-8583-4166-bba4-5df8466fd582"),
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            LanguageId = new Guid("e8f414c2-db64-424b-8954-c16cf4b763b9"),
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageId = new Guid("511fc232-7d06-480b-9c80-e0d9fcb05b37"),
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("c988543f-7b33-41cc-81b6-3b8e44434426"),
                            LanguageName = "Khmer"
                        },
                        new
                        {
                            LanguageId = new Guid("d564d962-8653-4fb0-8338-51d1b5364fe4"),
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = new Guid("a3f1b387-40e9-4b88-bd3f-1802e9f6b4ee"),
                            LanguageName = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("276c8a4c-297e-46c7-aa22-9f06d1d15bbb"),
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            LanguageId = new Guid("e2e6527c-5d76-424e-ad20-fb33f9a00d6f"),
                            LanguageName = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("931c2638-4669-4818-995f-330339ec89e5"),
                            LanguageName = "Lao"
                        },
                        new
                        {
                            LanguageId = new Guid("a85f0db2-8a72-4feb-8a8d-0114a480aeaa"),
                            LanguageName = "Latin"
                        },
                        new
                        {
                            LanguageId = new Guid("666354a9-f831-486b-81b7-9ecf67d9fbe5"),
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageId = new Guid("ba7cf3dc-0dbd-4833-a03e-c7cb3dd7152f"),
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = new Guid("1cab7cde-d9ed-4ea2-81af-882d56170eda"),
                            LanguageName = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = new Guid("c325dd6a-c87f-45ac-b540-c1ce222d7aea"),
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            LanguageId = new Guid("93b86025-ae64-4633-a605-b1165081fd3e"),
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            LanguageId = new Guid("56b34fa4-894c-4fd9-9eb2-56b735a2f7f6"),
                            LanguageName = "Malay"
                        },
                        new
                        {
                            LanguageId = new Guid("2b8f0db3-1e12-44f1-9520-c4695b05061c"),
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageId = new Guid("4f1b9dfe-291f-4443-83d1-407e2420e737"),
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageId = new Guid("77d1801d-e7e8-4b2c-b4e3-21bbeef8447a"),
                            LanguageName = "Maori"
                        },
                        new
                        {
                            LanguageId = new Guid("7307c698-0624-488e-a0c6-494a83f81085"),
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageId = new Guid("7793d049-eb3e-4ddb-90c2-6e6c8242f750"),
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            LanguageId = new Guid("fb3f4861-5240-47a8-b747-6f40e661f48b"),
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            LanguageId = new Guid("20551550-b092-4433-ba6f-6d03c5f66cdf"),
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = new Guid("9577fbea-1fe7-49ce-a8c5-73c5038500dd"),
                            LanguageName = "Odia"
                        },
                        new
                        {
                            LanguageId = new Guid("321c69c8-0db0-41ac-8f71-e1762137c04b"),
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            LanguageId = new Guid("f7244bb7-243d-4472-a083-5b96513e1bed"),
                            LanguageName = "Persian"
                        },
                        new
                        {
                            LanguageId = new Guid("3a2bf9f5-3230-49af-add3-c49b866ee3e8"),
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageId = new Guid("fc8d1bf4-9959-434a-b5b7-0ba3d5b8210a"),
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("d8f3e764-bfc6-4449-b539-db0e32422dda"),
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageId = new Guid("31ae9215-d143-4936-a92d-3aee26fa05d2"),
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageId = new Guid("46d9dcd7-be32-4d99-8abd-e0ee119191d6"),
                            LanguageName = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("ba2f3585-b314-44f2-ad9b-9684d7769370"),
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            LanguageId = new Guid("84cf0217-8329-4a14-9618-03617a75bb03"),
                            LanguageName = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = new Guid("a73ea57e-905c-4755-bf4c-c66fe2143572"),
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            LanguageId = new Guid("2294bbb1-5433-4609-a8bc-6b762b5eaa49"),
                            LanguageName = "Sesotho"
                        },
                        new
                        {
                            LanguageId = new Guid("c25ff3e5-d67a-404a-a4c2-d089e2327be0"),
                            LanguageName = "Shona"
                        },
                        new
                        {
                            LanguageId = new Guid("d8c082f3-e587-4818-812b-7604bd60594f"),
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            LanguageId = new Guid("16e7404a-b7e8-4634-b7ae-dfb75cfc8bc6"),
                            LanguageName = "Sinhala"
                        },
                        new
                        {
                            LanguageId = new Guid("e066fd93-d128-4942-90aa-bc05301d6dd6"),
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageId = new Guid("1f07074e-7003-4d1b-a30f-ec9f1ff87f27"),
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageId = new Guid("caf6a225-d1d8-4863-a42c-022fa5fad666"),
                            LanguageName = "Somali"
                        },
                        new
                        {
                            LanguageId = new Guid("c141e956-cfde-4dc2-8c62-33c765f1c2fe"),
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("8be44c90-bdf3-4284-a37e-972abd215df4"),
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            LanguageId = new Guid("141a885d-e950-4a41-ae95-243b77f0c79c"),
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            LanguageId = new Guid("2e64ecc2-ef83-4b95-9f0f-e8dde778fc0b"),
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = new Guid("bc1b37f3-3c33-4c1e-bbcf-d4ebc3a07e77"),
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("87f4880c-7c0b-4852-b3fb-e69edbbe3266"),
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageId = new Guid("e35b5640-4cbc-42ca-a285-cb65ef73df70"),
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            LanguageId = new Guid("68d2892f-75f4-4dcd-b6d2-542d81edde42"),
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageId = new Guid("93211bbb-bdbb-4fe8-9d8b-3b90909f5d64"),
                            LanguageName = "Thai"
                        },
                        new
                        {
                            LanguageId = new Guid("aeb53ab9-62f0-4eb1-9cae-111e6c3c6c9a"),
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            LanguageId = new Guid("228581a5-7556-4c2e-a560-8910e4d2acea"),
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            LanguageId = new Guid("a0799921-6ca8-4b78-ba74-a0b6caa13436"),
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("75b33899-065d-4fac-a273-894ed83b16a9"),
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageId = new Guid("14a89f72-ea00-4ef2-838a-f3e558a329b8"),
                            LanguageName = "Uyghur"
                        },
                        new
                        {
                            LanguageId = new Guid("8a214c2b-c277-4e80-87f6-1a5fb63766b3"),
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            LanguageId = new Guid("455fe596-f474-4a7e-8eb6-c1d160881dd1"),
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = new Guid("cb703db4-c0cb-4b92-beef-0ce9d41cafd2"),
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            LanguageId = new Guid("af1942f7-6a94-4790-856f-406da58e4ac6"),
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            LanguageId = new Guid("8094d416-5e4a-4a82-abbf-884b056f1edb"),
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            LanguageId = new Guid("d0329e32-b2ad-4bac-b954-b25ec867dd78"),
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            LanguageId = new Guid("156b3cd1-e69d-4d1f-bf6a-b626f3ab3a8c"),
                            LanguageName = "Zulu"
                        });
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Navigation("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });
#pragma warning restore 612, 618
        }
    }
}
