// <auto-generated />
using System;
using Hodrac_MVP_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hodrac_MVP_Backend.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20260218192213_FixCountryForeignKey")]
    partial class FixCountryForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestPeriodToVist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrencyId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("ef9f6716-0fe9-4d21-aebd-7edb6bd0c79d"),
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = new Guid("3aa1cd62-2dc4-497d-aced-ed15e9b991c1"),
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            LanguageId = new Guid("c3faa26b-6cb9-47b0-9fd5-4436fea79d72"),
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            LanguageId = new Guid("118ca133-1cdb-4335-82b1-4b9e5924dc6a"),
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            LanguageId = new Guid("81e191f6-1f32-419c-a109-88d5d7bd0571"),
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("1ff305eb-79d3-4e3f-bdd7-14d701676af9"),
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            LanguageId = new Guid("628b80b0-c656-43a9-95fe-a05838e7c26e"),
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("bc8b06c2-d6b2-4dd6-8ee7-c1dda53bc2a4"),
                            LanguageName = "Basque"
                        },
                        new
                        {
                            LanguageId = new Guid("d0b1f016-c29c-4622-b04a-2d054c4ff668"),
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("67fa8201-e376-45c6-8bfa-e8564517da2c"),
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            LanguageId = new Guid("a9c5854d-a5b5-42cf-953e-df05a1ca9787"),
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            LanguageId = new Guid("21205e99-e7db-47bf-9de3-af16ef66edca"),
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = new Guid("3f2d5c85-0f61-461e-94d8-052bbb32d4f8"),
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            LanguageId = new Guid("67768d40-63c4-4ae3-992a-0e8c3b174c6a"),
                            LanguageName = "Catalan"
                        },
                        new
                        {
                            LanguageId = new Guid("aa5fc42a-92df-4369-bc2a-46916175deda"),
                            LanguageName = "Cebuano"
                        },
                        new
                        {
                            LanguageId = new Guid("a733525c-80a6-4327-9879-dce477211162"),
                            LanguageName = "Chichewa"
                        },
                        new
                        {
                            LanguageId = new Guid("53bff35f-1b48-4620-a75d-7c0589ced6fa"),
                            LanguageName = "Chinese (Mandarin)"
                        },
                        new
                        {
                            LanguageId = new Guid("24747e82-c82e-44ca-a835-11a8ec29095b"),
                            LanguageName = "Chinese (Cantonese)"
                        },
                        new
                        {
                            LanguageId = new Guid("c344db8f-6963-462a-8736-0fccd75d0070"),
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            LanguageId = new Guid("90fbac0e-b6ca-46f7-854b-6e1fb08257f5"),
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageId = new Guid("6e049c74-a532-4a41-8ee6-279631faedf0"),
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageId = new Guid("ef1e3fe8-fdf2-4240-adcf-7d4fd5593bf6"),
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageId = new Guid("40cdc829-29d4-43ab-b62a-3ec640af0e4e"),
                            LanguageName = "Dari"
                        },
                        new
                        {
                            LanguageId = new Guid("326150c2-5f36-4289-8af2-5279d8ef5712"),
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageId = new Guid("fcf13ee6-e817-4345-aedf-bf4e98e84316"),
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("bc66dfde-e930-4f10-9619-7ec3c3cbfc4b"),
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            LanguageId = new Guid("ecae7de0-3830-41de-a97f-108e07115604"),
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageId = new Guid("41cf5c42-c290-4e32-a367-e0b1941b97b0"),
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            LanguageId = new Guid("5c6e37b0-7581-43e5-8986-9a6f8cc72e28"),
                            LanguageName = "Filipino"
                        },
                        new
                        {
                            LanguageId = new Guid("9b3bc1a1-4a07-45b0-a463-4cd1e57ea8ee"),
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageId = new Guid("b5d5437d-d615-4392-b9be-3e45e67471e5"),
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("ab74b800-6a20-4933-8b71-6d65dc8856a3"),
                            LanguageName = "Frisian"
                        },
                        new
                        {
                            LanguageId = new Guid("85de35b2-2db5-4893-83b7-d42d66d21f6e"),
                            LanguageName = "Galician"
                        },
                        new
                        {
                            LanguageId = new Guid("3efd64ba-dbbf-4300-a49d-52f16b8cca0c"),
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("cdbbacdf-77d5-43a6-a9fe-2b0becde506f"),
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("72d7bec3-3648-480a-8195-42763119248a"),
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageId = new Guid("d45d1268-de87-4b0a-b1b9-a969cd20a498"),
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            LanguageId = new Guid("40ffe8e3-54ee-4d8f-b364-c955248086ab"),
                            LanguageName = "Haitian Creole"
                        },
                        new
                        {
                            LanguageId = new Guid("39768953-b5c0-48cf-b52b-593114205e93"),
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            LanguageId = new Guid("54dee145-3967-42b0-8253-8da3edef4217"),
                            LanguageName = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = new Guid("e0a81968-6e3f-4846-99fc-b53450f56cc3"),
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            LanguageId = new Guid("7aaa2abd-d299-499a-837f-408bde3a2773"),
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageId = new Guid("cddff1cf-e5b8-4994-ab6c-524275465c4b"),
                            LanguageName = "Hmong"
                        },
                        new
                        {
                            LanguageId = new Guid("003bd571-4d0d-4234-a667-3df269bc6aa9"),
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("33a70d06-a8e2-4425-abae-f4440f095b2e"),
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            LanguageId = new Guid("61c73526-089d-4d52-8124-5dd8c187a93a"),
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            LanguageId = new Guid("32b4f564-661a-456f-9357-c775ad40d69c"),
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            LanguageId = new Guid("2dd276b8-6ba6-42e5-a4c8-51af8b784c63"),
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageId = new Guid("5a36f6ec-8abb-4809-89c2-df24779784d0"),
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("afea1cdc-adb5-4745-86a5-1047e6e9b116"),
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("6d66403d-37cc-4152-be92-19dd40134b8d"),
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            LanguageId = new Guid("3fada422-80c8-4ec6-ac11-c15aa35fa096"),
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageId = new Guid("534e3d0b-a172-438f-a349-e8a6ae6caa11"),
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("577ff31e-9b9a-46c4-a328-80197c296d94"),
                            LanguageName = "Khmer"
                        },
                        new
                        {
                            LanguageId = new Guid("e8f328fc-cb40-44ab-b293-68240aeb1b49"),
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = new Guid("2518bc66-4eb0-47f7-9125-9853c5ed5597"),
                            LanguageName = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("e546b6f6-b952-493c-b505-be4c255d551e"),
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            LanguageId = new Guid("7a28dacf-b9b3-41e8-9c8c-e3628382ac42"),
                            LanguageName = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("6d650958-6a36-4373-9741-62646afa5f92"),
                            LanguageName = "Lao"
                        },
                        new
                        {
                            LanguageId = new Guid("6d7a2873-e2e9-4ce5-b17a-f6501fa34df7"),
                            LanguageName = "Latin"
                        },
                        new
                        {
                            LanguageId = new Guid("97a1c826-ca50-4f95-84b1-23ac2503699b"),
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageId = new Guid("85064b65-c48a-4c2b-af4b-8d48d4aa6cbd"),
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = new Guid("9c477989-0335-460d-b9c2-65ba17f42af7"),
                            LanguageName = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = new Guid("146caa8c-09e1-4f13-8b00-ca219b30140e"),
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            LanguageId = new Guid("374d0e46-e8d3-4814-985c-9fb020a3a1b8"),
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            LanguageId = new Guid("a86e1bbd-7b79-4114-a2a3-3ef70e44264a"),
                            LanguageName = "Malay"
                        },
                        new
                        {
                            LanguageId = new Guid("55c07e1b-5fb0-4aee-995a-49f134531152"),
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageId = new Guid("88da282b-96e2-423b-8a4b-ea4d45ac7061"),
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageId = new Guid("59409e6b-9170-4b3e-8cea-9a69192ffd19"),
                            LanguageName = "Maori"
                        },
                        new
                        {
                            LanguageId = new Guid("31fa0ece-055d-4767-98a5-b2ddd659dafe"),
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageId = new Guid("65aeca4d-29ba-4542-837c-e3f99eb00eea"),
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            LanguageId = new Guid("a0d30334-47ec-4566-b172-f05edcec5369"),
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            LanguageId = new Guid("e023c813-a22e-425b-a82b-9e669cb3a992"),
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = new Guid("7215035c-d863-493a-bc0a-7fb350411c98"),
                            LanguageName = "Odia"
                        },
                        new
                        {
                            LanguageId = new Guid("8cb726c0-354c-4370-97c1-2b35efde6107"),
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            LanguageId = new Guid("f40999f3-d416-4c63-8c4e-4d223f7f1310"),
                            LanguageName = "Persian"
                        },
                        new
                        {
                            LanguageId = new Guid("df4ce3c5-0ce8-44e7-8d96-3f766f69ffcc"),
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageId = new Guid("bf8a5288-b030-4e44-95c9-67584e18a1b8"),
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("a49ad3fa-50ae-45f5-86ae-f105fac333f4"),
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageId = new Guid("dfb69a10-73e0-48b7-b4cc-c84eef44b88f"),
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageId = new Guid("47740e21-c441-4abb-a7be-2e6278b10745"),
                            LanguageName = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("f0d6c937-4ad3-4ba8-a4a0-6aff113eedca"),
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            LanguageId = new Guid("074a8236-c26b-4c95-8827-b055fd635ea0"),
                            LanguageName = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = new Guid("52f18624-7555-43d8-825e-79531f92b9a9"),
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            LanguageId = new Guid("f1a22541-852c-40b0-8b7f-8d657aa18638"),
                            LanguageName = "Sesotho"
                        },
                        new
                        {
                            LanguageId = new Guid("3d640ee8-9bc4-4cb5-9602-0193845ac42a"),
                            LanguageName = "Shona"
                        },
                        new
                        {
                            LanguageId = new Guid("9b1a2fd4-a2a8-48d9-8803-97e9ac84d09b"),
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            LanguageId = new Guid("b7ad3af9-a8d9-46b0-9b9c-103967ce93b2"),
                            LanguageName = "Sinhala"
                        },
                        new
                        {
                            LanguageId = new Guid("fc3a9739-e288-4f11-93e1-a1885ad61053"),
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageId = new Guid("e7e8db2b-f093-415a-87f2-dc41ca3c0587"),
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageId = new Guid("cd791d51-0a13-406a-9e27-966ba5566937"),
                            LanguageName = "Somali"
                        },
                        new
                        {
                            LanguageId = new Guid("b2744ae8-935c-4435-ad88-7fb839a9f25f"),
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("203fbdf2-f1ce-4468-8a71-99915a77dada"),
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            LanguageId = new Guid("d9bf915b-7846-4494-8956-34fe6a0fe977"),
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            LanguageId = new Guid("46f606ab-4c2f-4065-af76-50b80d33e29f"),
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = new Guid("2425aa5d-2759-4f04-8edf-5ba666b626fb"),
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("2a13b85d-1fc8-4a18-bf3b-6dfdf02c65c3"),
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageId = new Guid("b4120956-850f-4468-9c4e-9fb36e9c98f9"),
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            LanguageId = new Guid("cbb6e42a-8e4c-499b-ad0a-4f6f60565cfa"),
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageId = new Guid("28bb83f8-71c9-487c-8772-3f12f07ae2d1"),
                            LanguageName = "Thai"
                        },
                        new
                        {
                            LanguageId = new Guid("1ec7d542-271c-44b9-ab10-530b85b67d9d"),
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            LanguageId = new Guid("071523b9-818c-4bdb-a865-a4a13844c078"),
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            LanguageId = new Guid("458264d7-7305-437a-81dd-0a4fe9e76fc9"),
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("1ffbbec6-6491-4f19-b4bd-de0331c5520a"),
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageId = new Guid("c98ec2a6-6c43-4d42-b817-567bcb0bf08d"),
                            LanguageName = "Uyghur"
                        },
                        new
                        {
                            LanguageId = new Guid("cc5c230d-87ed-4223-b728-4c66e6d7a184"),
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            LanguageId = new Guid("d0a310c5-ea2b-4db2-b6d1-e05441bd9b38"),
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = new Guid("56aa45c9-5c5d-4e13-8696-c65badbcf782"),
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            LanguageId = new Guid("02b31e5e-56cf-4c7f-ae6c-abbc9be8bde2"),
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            LanguageId = new Guid("dca3cb61-c91c-4729-8b0c-570586fe2c89"),
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            LanguageId = new Guid("897e9258-c816-469c-a666-7bc8b1630d7a"),
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            LanguageId = new Guid("fa6cc8aa-777c-407f-ac6b-8b41146a179b"),
                            LanguageName = "Zulu"
                        });
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Navigation("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });
#pragma warning restore 612, 618
        }
    }
}
