// <auto-generated />
using System;
using Hodrac_MVP_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hodrac_MVP_Backend.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20260217123908_SeedLanguages")]
    partial class SeedLanguages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestPeriodToVist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SafetyLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrencyId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("009b909e-829e-483b-a24e-818beda12c5c"),
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = new Guid("816894d2-91c2-45d2-a201-724e5e694e83"),
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            LanguageId = new Guid("4bc6f917-0b5f-499f-b556-68316cd682a8"),
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            LanguageId = new Guid("582645f6-bff3-4f13-aa0a-9190bf2090c4"),
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            LanguageId = new Guid("b2ddf799-146a-4cc6-9eba-97cd702682a6"),
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("539d2e24-fc8a-4b61-8788-a6be445adcf8"),
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            LanguageId = new Guid("0ccb123c-7a0d-4ffc-8614-137a8d0739cc"),
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("2936d03d-fa31-4ce8-9c95-a3e1015b2a8c"),
                            LanguageName = "Basque"
                        },
                        new
                        {
                            LanguageId = new Guid("65ff9b9c-c6f6-457a-a3bf-510d9b6c0e1b"),
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("f6d0acba-f8dd-41ef-913d-765fdf871e4c"),
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            LanguageId = new Guid("f537c46f-89a4-4b25-91f0-68a375118db0"),
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            LanguageId = new Guid("ae018ced-a132-4027-a5af-ad0a32528b9e"),
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = new Guid("e716b847-432c-4d44-803e-dc1700f18144"),
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            LanguageId = new Guid("bbfcd81a-ed5e-4b87-a0d3-876726160ddf"),
                            LanguageName = "Catalan"
                        },
                        new
                        {
                            LanguageId = new Guid("ccb8a8fa-0c84-4e51-8274-78c5e3f207d0"),
                            LanguageName = "Cebuano"
                        },
                        new
                        {
                            LanguageId = new Guid("98e96c89-9875-44b0-a565-fb8c07c4afaf"),
                            LanguageName = "Chichewa"
                        },
                        new
                        {
                            LanguageId = new Guid("01a8671b-ec40-48d4-9259-5595ccfd537c"),
                            LanguageName = "Chinese (Mandarin)"
                        },
                        new
                        {
                            LanguageId = new Guid("fb99a084-a3d3-4d0e-8f2f-3a5dd6536759"),
                            LanguageName = "Chinese (Cantonese)"
                        },
                        new
                        {
                            LanguageId = new Guid("26b5b8a6-46c9-45ef-9d36-5ac92304f52f"),
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            LanguageId = new Guid("834796dc-2f71-4b10-9096-bc48951940a5"),
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            LanguageId = new Guid("93456d8b-86fe-4219-9448-05e0178b47d5"),
                            LanguageName = "Czech"
                        },
                        new
                        {
                            LanguageId = new Guid("c3e535ad-8b05-4ce6-a302-fdb830605ea3"),
                            LanguageName = "Danish"
                        },
                        new
                        {
                            LanguageId = new Guid("7284fb11-fc82-490b-b8be-f73b0398ccde"),
                            LanguageName = "Dari"
                        },
                        new
                        {
                            LanguageId = new Guid("f3707b69-47c4-44f8-b462-cbcad60b15c3"),
                            LanguageName = "Dutch"
                        },
                        new
                        {
                            LanguageId = new Guid("8ef81c00-dc64-450c-aa0b-b12682bc0777"),
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("d6544404-3f7b-4ae8-bb7d-e0398c761e0e"),
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            LanguageId = new Guid("a966aec5-e74b-46ff-90b4-027f259e19a6"),
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            LanguageId = new Guid("eb357206-83f2-412a-89db-cb2645321562"),
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            LanguageId = new Guid("dca56cfa-838c-49ba-b88f-74ef5c048f33"),
                            LanguageName = "Filipino"
                        },
                        new
                        {
                            LanguageId = new Guid("6826088a-bd79-44f3-826d-34391aa59f44"),
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            LanguageId = new Guid("db6ef275-14d8-40ec-a0bd-6ee9be77ae9b"),
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("b94059a8-cdf7-418e-b0d2-a47e7a42512e"),
                            LanguageName = "Frisian"
                        },
                        new
                        {
                            LanguageId = new Guid("b48c2526-db17-4569-a679-29250b4dcebc"),
                            LanguageName = "Galician"
                        },
                        new
                        {
                            LanguageId = new Guid("931249e8-a620-4ad4-9628-3d9ec96019f3"),
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("8fe5deaf-d519-4e34-b830-c869024773ba"),
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("a6eba4d0-41ec-4318-a4e0-6caea6e5d44a"),
                            LanguageName = "Greek"
                        },
                        new
                        {
                            LanguageId = new Guid("182d54bd-943f-4e5d-a743-ed21d4393326"),
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            LanguageId = new Guid("9ecc72d2-a48b-4f4c-9d4e-6e19fadfd130"),
                            LanguageName = "Haitian Creole"
                        },
                        new
                        {
                            LanguageId = new Guid("a815e0e0-1809-454a-9840-db3a87678646"),
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            LanguageId = new Guid("0969a63b-881d-4a4f-b4af-40eb64933218"),
                            LanguageName = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = new Guid("1e939af9-ab04-44d9-beff-e69eed27f7ce"),
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            LanguageId = new Guid("b5531560-d7ed-4765-b435-0d43ea8b3b8a"),
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageId = new Guid("16e3c394-9486-4543-a919-3455a59d0cce"),
                            LanguageName = "Hmong"
                        },
                        new
                        {
                            LanguageId = new Guid("d900f2dc-8017-4de3-a64c-a9c112628457"),
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("9025e5b8-f0d3-47dc-a8b6-08406c0f81cb"),
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            LanguageId = new Guid("5810fdb6-316b-4974-841f-28df01e8115a"),
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            LanguageId = new Guid("5f9b3002-15e5-42a9-b5bf-98fb66276925"),
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            LanguageId = new Guid("23cfdace-207c-4ebf-b876-8ee4a5f14b23"),
                            LanguageName = "Irish"
                        },
                        new
                        {
                            LanguageId = new Guid("0d8511f5-8136-47c8-9d61-bbdf168f6803"),
                            LanguageName = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("39931ae3-deba-43ee-a448-e20181c8e76a"),
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("3cb019ac-b82a-48a6-ad6c-a7f2f2353923"),
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            LanguageId = new Guid("79e0ccaf-0dd3-4685-bae9-6e871469a166"),
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageId = new Guid("687db95a-2000-4c51-9d70-41fef88169cf"),
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("341224f5-f74a-40dd-83c4-fcc36ca83d1f"),
                            LanguageName = "Khmer"
                        },
                        new
                        {
                            LanguageId = new Guid("6d57f9a1-abd7-4f07-94dc-a4aecaad6fec"),
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = new Guid("3bb8dc11-d2a8-41dd-95cf-5b0492e6eda4"),
                            LanguageName = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("19a47393-1bf1-4c92-966f-d7fd83ef82c3"),
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            LanguageId = new Guid("543cbd15-aa33-452f-90b0-81a340a916b0"),
                            LanguageName = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("2768921d-570b-4af7-a413-cda99435eea1"),
                            LanguageName = "Lao"
                        },
                        new
                        {
                            LanguageId = new Guid("6e5821e3-7acc-4c76-81f2-d05468a42e0f"),
                            LanguageName = "Latin"
                        },
                        new
                        {
                            LanguageId = new Guid("515582ec-6cee-410b-b4d8-55b888dccf89"),
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            LanguageId = new Guid("ced40db0-363f-4f93-a01f-91b30175c70e"),
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = new Guid("d80d04e2-c425-4291-9c78-2e4b53e4c8cb"),
                            LanguageName = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = new Guid("58e65cff-af0d-4750-932f-04ac9203b202"),
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            LanguageId = new Guid("9c4b564d-7288-4771-9d68-beccd42cab57"),
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            LanguageId = new Guid("74ea65eb-ed99-437b-8f61-5c5c9d79edda"),
                            LanguageName = "Malay"
                        },
                        new
                        {
                            LanguageId = new Guid("f6756ae1-fade-422b-837b-e1aae84d152d"),
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageId = new Guid("e57e78df-6192-423c-9d3f-913ca66701b2"),
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            LanguageId = new Guid("6cd829fd-629f-4de8-9afd-6985496c4051"),
                            LanguageName = "Maori"
                        },
                        new
                        {
                            LanguageId = new Guid("162ec2f0-b7bb-4fab-b8a8-be998e7a79a2"),
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageId = new Guid("46b157f4-f6e2-4208-b710-6cc5131f001d"),
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            LanguageId = new Guid("bd52bdbe-c4bb-4449-9e52-6169c9304d3b"),
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            LanguageId = new Guid("a173504f-be00-4982-be88-4a50d9271c24"),
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = new Guid("8dfef08f-a18a-4a7e-b9d2-9360e37dc804"),
                            LanguageName = "Odia"
                        },
                        new
                        {
                            LanguageId = new Guid("36bf985e-c569-469b-bd72-de3616fe706b"),
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            LanguageId = new Guid("8e76d742-f96a-41fe-815d-e0df13b7af4e"),
                            LanguageName = "Persian"
                        },
                        new
                        {
                            LanguageId = new Guid("8b51f7ed-9441-4cd1-911c-6b177546ea3c"),
                            LanguageName = "Polish"
                        },
                        new
                        {
                            LanguageId = new Guid("17a90c16-7850-4f5d-ac69-0ff0168c2a40"),
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("b41e7e8c-275c-400b-8114-7c00246078f7"),
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageId = new Guid("4b02dde5-b942-4872-8478-8bd120e06ace"),
                            LanguageName = "Romanian"
                        },
                        new
                        {
                            LanguageId = new Guid("02e85773-e791-4685-a043-20141f6fe48e"),
                            LanguageName = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("3bc56107-d777-4035-9df2-a0f745f74899"),
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            LanguageId = new Guid("77f3b37a-2745-4c54-8fa9-39b00d2ab34f"),
                            LanguageName = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = new Guid("56d407f1-1bc0-4a73-a988-c8bd0c2666b6"),
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            LanguageId = new Guid("2b08d03d-4efa-4d1b-8873-76aa0f0adcd2"),
                            LanguageName = "Sesotho"
                        },
                        new
                        {
                            LanguageId = new Guid("514afbbd-37fd-4d20-bff4-a0574a67127d"),
                            LanguageName = "Shona"
                        },
                        new
                        {
                            LanguageId = new Guid("e8637d8a-eee1-46ae-bb87-9f1c1fa74109"),
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            LanguageId = new Guid("4dee3394-bbc7-4ed0-9541-7c265d43f7ec"),
                            LanguageName = "Sinhala"
                        },
                        new
                        {
                            LanguageId = new Guid("5f6bc256-5996-4c84-a3da-62c5cbeb4cfa"),
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            LanguageId = new Guid("c390f2a9-9120-473d-bf12-937ed076bfe0"),
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            LanguageId = new Guid("663613d4-14ac-4d78-8bca-08fb49e314eb"),
                            LanguageName = "Somali"
                        },
                        new
                        {
                            LanguageId = new Guid("62fccf19-1d43-462a-9768-00cd9f326fec"),
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("1c84e4bd-4b3c-453f-a502-1d496763f1ac"),
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            LanguageId = new Guid("67904680-0c9b-4417-997e-e45f51c8c618"),
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            LanguageId = new Guid("5db9c67b-cbf3-4943-9ae6-5db1a9cd95d3"),
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = new Guid("1ad1d234-65ba-4f5c-a724-576cc73ed2f2"),
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("9e3615a6-5576-40c1-a877-614f64440727"),
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageId = new Guid("d43315a9-b5f0-472a-a59a-4952395fcb21"),
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            LanguageId = new Guid("c35571b9-65be-4a85-aadc-1b578ef1a736"),
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageId = new Guid("4a92fb57-8ef9-41a8-8b0b-e93d2f3f2f34"),
                            LanguageName = "Thai"
                        },
                        new
                        {
                            LanguageId = new Guid("7fcb1776-b96a-4872-b600-d898a49b3d25"),
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            LanguageId = new Guid("8130e7eb-3971-4ff4-aa01-3b58dad382cf"),
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            LanguageId = new Guid("072b0b50-b474-406e-8de6-6e21ca42c49c"),
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("c7d339b2-63bb-4a70-9727-032ca4c987eb"),
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageId = new Guid("6d9ebdf3-130a-4539-9f01-2b153d4b4e28"),
                            LanguageName = "Uyghur"
                        },
                        new
                        {
                            LanguageId = new Guid("772c4036-d0e7-49ee-b5c6-e9c29d13b8f0"),
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            LanguageId = new Guid("ffe2c1b6-ebdb-4b47-bca7-072509dff172"),
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = new Guid("5620f9a3-6f2c-4089-947e-192a044a8db7"),
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            LanguageId = new Guid("d9864a21-5957-4bb3-8f55-ebc35914bce8"),
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            LanguageId = new Guid("45fd39aa-d9dc-416d-b5df-809f41a692f5"),
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            LanguageId = new Guid("8e8bee65-ee49-490e-bce6-3b4dea52964c"),
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            LanguageId = new Guid("d0ffc022-b927-4e63-b987-b85e02ee0cd9"),
                            LanguageName = "Zulu"
                        });
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCategory", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCity", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.City", "City")
                        .WithMany("DestinationCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationCurrency", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Currency", "Currency")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationCurrencies")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationLanguage", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Language", "Language")
                        .WithMany("DestinationLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.DestinationTag", b =>
                {
                    b.HasOne("Hodrac_MVP_Backend.Models.Destination", "Destination")
                        .WithMany("DestinationTags")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodrac_MVP_Backend.Models.Tag", "Tag")
                        .WithMany("DestinationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.City", b =>
                {
                    b.Navigation("DestinationCities");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Currency", b =>
                {
                    b.Navigation("DestinationCurrencies");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Destination", b =>
                {
                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationCities");

                    b.Navigation("DestinationCurrencies");

                    b.Navigation("DestinationLanguages");

                    b.Navigation("DestinationTags");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Language", b =>
                {
                    b.Navigation("DestinationLanguages");
                });

            modelBuilder.Entity("Hodrac_MVP_Backend.Models.Tag", b =>
                {
                    b.Navigation("DestinationTags");
                });
#pragma warning restore 612, 618
        }
    }
}
